-- --------------------------------------------------------------------------------
-- Webhooks + ClusterEnrollmentTokens + ImpersonationSessions (stage-2).
--
-- - webhook_endpoints: per-tenant outbound HTTP webhooks for
--   tenant-scoped events. Separate from notification_channels (those
--   are user-targeted; these are infra-targeted).
-- - cluster_enrollment_tokens: tokens generated by an admin to
--   bootstrap a new node into the cluster. Single-use; consumed_at
--   tracks redemption. NOT tenant-scoped (cluster is global).
-- - impersonation_sessions: super-admin impersonation audit trail
--   with TOTP gating and idle/absolute session deadlines.
-- --------------------------------------------------------------------------------

CREATE TABLE webhook_endpoints (
    id VARCHAR(64) PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name          TEXT NOT NULL,
    url           TEXT NOT NULL,
    secret        TEXT,                                                       -- HMAC signing secret (encrypted)
    events        TEXT NOT NULL DEFAULT '[]',                                 -- JSON array of subscribed event types
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE (tenant_id, name)
 ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_webhook_endpoints_tenant ON webhook_endpoints (tenant_id);

CREATE TABLE cluster_enrollment_tokens (
    id VARCHAR(64) PRIMARY KEY,
    token_hash         TEXT NOT NULL UNIQUE,                                  -- the actual token is returned once at create; only the hash persists
    created_by         TEXT,                                                  -- user_id of issuer
    expires_at DATETIME(6) NOT NULL,
    consumed_at        TEXT,                                                  -- when redeemed
    consumed_by_node_id TEXT,                                                 -- which node redeemed it
    revoked_at         TEXT,
    notes              TEXT NOT NULL DEFAULT '',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
 ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_cluster_tokens_unconsumed ON cluster_enrollment_tokens (expires_at) WHERE consumed_at IS NULL AND revoked_at IS NULL;

CREATE TABLE impersonation_sessions (
    id VARCHAR(64) PRIMARY KEY,
    super_admin_id  TEXT NOT NULL,
    tenant_id VARCHAR(64) REFERENCES tenants(id) ON DELETE SET NULL,           -- NULL = no specific tenant
    user_id         TEXT,                                                     -- impersonated user (NULL = read-only impersonation)
    reason          TEXT NOT NULL DEFAULT '',
    started_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    expires_at DATETIME(6) NOT NULL,
    last_active_at  TEXT,
    ended_at        TEXT,
    end_reason      TEXT                                                      -- explicit_exit | idle_timeout | absolute_timeout | revoked
 ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX idx_impersonation_super_admin ON impersonation_sessions (super_admin_id);
CREATE INDEX idx_impersonation_active      ON impersonation_sessions (expires_at) WHERE ended_at IS NULL;

INSERT IGNORE INTO schema_versions (version, dirty) VALUES (21, 0);
