-- 000049_permissions_gap_fill.up.sql
-- Backfill: seed the v2 permission catalog (singular resource names, granular actions).
-- All 103 entries originate from daemon code; source = 'built-in'.
-- ON CONFLICT(id) is safe to run on fresh installs and upgrades alike.
INSERT INTO permissions (id, resource, action, description, source) VALUES
    ('service:read', 'service', 'read', 'View service configuration and metadata', 'built-in'),
    ('service:write', 'service', 'write', 'Create and update services', 'built-in'),
    ('service:delete', 'service', 'delete', 'Delete services', 'built-in'),
    ('service:force-reload', 'service', 'force-reload', 'Force a reload of service configuration into Caddy', 'built-in'),
    ('route:read', 'route', 'read', 'View route configuration', 'built-in'),
    ('route:write', 'route', 'write', 'Create and update routes', 'built-in'),
    ('route:delete', 'route', 'delete', 'Delete routes', 'built-in'),
    ('route:publish', 'route', 'publish', 'Publish route changes to live traffic', 'built-in'),
    ('route:attach-policy', 'route', 'attach-policy', 'Attach or detach access policies from routes', 'built-in'),
    ('policy:read', 'policy', 'read', 'View access and RBAC policies', 'built-in'),
    ('policy:write', 'policy', 'write', 'Create and update policies', 'built-in'),
    ('policy:delete', 'policy', 'delete', 'Delete policies', 'built-in'),
    ('user:read', 'user', 'read', 'View user profiles and membership state', 'built-in'),
    ('user:invite', 'user', 'invite', 'Invite new users to the tenant', 'built-in'),
    ('user:disable', 'user', 'disable', 'Disable or re-enable user accounts', 'built-in'),
    ('user:impersonate', 'user', 'impersonate', 'Impersonate another user within the tenant (super-admin only)', 'built-in'),
    ('user:update-own', 'user', 'update-own', 'Update own profile (name, avatar, preferences, password)', 'built-in'),
    ('role:read', 'role', 'read', 'View roles and their permission grants', 'built-in'),
    ('role:write', 'role', 'write', 'Create and update roles', 'built-in'),
    ('role:delete', 'role', 'delete', 'Delete roles', 'built-in'),
    ('api-key:read', 'api-key', 'read', 'View API key metadata (not the secret)', 'built-in'),
    ('api-key:create', 'api-key', 'create', 'Create new API keys', 'built-in'),
    ('api-key:delete', 'api-key', 'delete', 'Revoke and delete API keys', 'built-in'),
    ('session:read', 'session', 'read', 'View active sessions', 'built-in'),
    ('session:revoke', 'session', 'revoke', 'Revoke active sessions', 'built-in'),
    ('plugin-signer:read', 'plugin-signer', 'read', 'View plugin signer allow-list entries', 'built-in'),
    ('plugin-signer:write', 'plugin-signer', 'write', 'Create, update, verify, or revoke plugin signers', 'built-in'),
    ('plugin-signer:delete', 'plugin-signer', 'delete', 'Delete plugin signers (only when no plugins reference them)', 'built-in'),
    ('plugin:read', 'plugin', 'read', 'View installed plugins and the marketplace catalog', 'built-in'),
    ('plugin:install', 'plugin', 'install', 'Install plugins from the marketplace', 'built-in'),
    ('plugin:uninstall', 'plugin', 'uninstall', 'Uninstall plugins', 'built-in'),
    ('plugin:enable', 'plugin', 'enable', 'Enable or disable installed plugins', 'built-in'),
    ('plugin:register-permission', 'plugin', 'register-permission', 'Allow a plugin to register custom permissions (super-admin only)', 'built-in'),
    ('tenant:read', 'tenant', 'read', 'View the current tenant record and settings', 'built-in'),
    ('tenant:write', 'tenant', 'write', 'Update tenant settings (name, url mode, theme, logo)', 'built-in'),
    ('tenant:switch', 'tenant', 'switch', 'Switch the active tenant context', 'built-in'),
    ('tenant-auth:read', 'tenant-auth', 'read', 'View tenant authentication policy', 'built-in'),
    ('tenant-auth:write', 'tenant-auth', 'write', 'Update tenant authentication policy (TOTP, password, session)', 'built-in'),
    ('tenant:create', 'tenant', 'create', 'Create a new tenant (super-admin only)', 'built-in'),
    ('admin:cross-tenant-read', 'admin', 'cross-tenant-read', 'Read data across tenant boundaries (super-admin only)', 'built-in'),
    ('admin:cross-tenant-write', 'admin', 'cross-tenant-write', 'Write data across tenant boundaries (super-admin only)', 'built-in'),
    ('audit:read', 'audit', 'read', 'View the audit log', 'built-in'),
    ('audit:read-sensitive', 'audit', 'read-sensitive', 'View sensitive audit fields (IP, user-agent, payload bodies) and free-text search payloads', 'built-in'),
    ('audit:export', 'audit', 'export', 'Export audit entries as CSV or JSONL', 'built-in'),
    ('audit:retention:read', 'audit:retention', 'read', 'View the audit retention configuration', 'built-in'),
    ('audit:retention:write', 'audit:retention', 'write', 'Change the audit retention configuration', 'built-in'),
    ('site:read', 'site', 'read', 'View sites', 'built-in'),
    ('site:write', 'site', 'write', 'Create or modify sites', 'built-in'),
    ('site:delete', 'site', 'delete', 'Delete sites', 'built-in'),
    ('middleware:read', 'middleware', 'read', 'View middlewares', 'built-in'),
    ('middleware:write', 'middleware', 'write', 'Create or modify middlewares', 'built-in'),
    ('middleware:delete', 'middleware', 'delete', 'Delete middlewares', 'built-in'),
    ('ai-provider:read', 'ai-provider', 'read', 'View LLM providers', 'built-in'),
    ('ai-provider:write', 'ai-provider', 'write', 'Configure LLM providers', 'built-in'),
    ('ai-provider:delete', 'ai-provider', 'delete', 'Remove LLM providers', 'built-in'),
    ('ai-agent:read', 'ai-agent', 'read', 'View AI agents', 'built-in'),
    ('ai-agent:write', 'ai-agent', 'write', 'Create or modify AI agents', 'built-in'),
    ('ai-agent:delete', 'ai-agent', 'delete', 'Remove AI agents', 'built-in'),
    ('ai-agent:invoke', 'ai-agent', 'invoke', 'Invoke AI agents', 'built-in'),
    ('ai-tool:read', 'ai-tool', 'read', 'View AI tools', 'built-in'),
    ('ai-tool:write', 'ai-tool', 'write', 'Create or modify AI tools', 'built-in'),
    ('ai-tool:delete', 'ai-tool', 'delete', 'Remove AI tools', 'built-in'),
    ('ai-trace:read', 'ai-trace', 'read', 'View AI traces', 'built-in'),
    ('ai-trace:read-sensitive', 'ai-trace', 'read-sensitive', 'View AI trace prompt/completion content', 'built-in'),
    ('ai-rate-limit:read', 'ai-rate-limit', 'read', 'View semantic rate limits', 'built-in'),
    ('ai-rate-limit:write', 'ai-rate-limit', 'write', 'Configure semantic rate limits', 'built-in'),
    ('mcp-server:read', 'mcp-server', 'read', 'View MCP servers', 'built-in'),
    ('mcp-server:write', 'mcp-server', 'write', 'Configure MCP servers', 'built-in'),
    ('mcp-server:delete', 'mcp-server', 'delete', 'Remove MCP servers', 'built-in'),
    ('dashboard:read', 'dashboard', 'read', 'View dashboards', 'built-in'),
    ('dashboard:write', 'dashboard', 'write', 'Create and update dashboards and widgets', 'built-in'),
    ('dashboard:delete', 'dashboard', 'delete', 'Delete dashboards', 'built-in'),
    ('dashboard:share', 'dashboard', 'share', 'Change dashboard scope / role sharing', 'built-in'),
    ('dashboard:set-default', 'dashboard', 'set-default', 'Mark a dashboard as the tenant default', 'built-in'),
    ('notification:read', 'notification', 'read', 'View notifications in the inbox', 'built-in'),
    ('notification:manage-own', 'notification', 'manage-own', 'Mark own notifications read/unread and archive/unarchive them', 'built-in'),
    ('notification-channel:read', 'notification-channel', 'read', 'View notification delivery channels and their configuration', 'built-in'),
    ('notification-channel:write', 'notification-channel', 'write', 'Create, update, or delete notification delivery channels', 'built-in'),
    ('notification-channel:test', 'notification-channel', 'test', 'Send a test notification through a channel', 'built-in'),
    ('notification-routing:read', 'notification-routing', 'read', 'View notification routing rules', 'built-in'),
    ('notification-routing:write', 'notification-routing', 'write', 'Create, update, delete, or reorder notification routing rules', 'built-in'),
    ('notification-log:read', 'notification-log', 'read', 'View the notification delivery log', 'built-in'),
    ('notification:admin', 'notification', 'admin', 'Manage tenant-wide notification configuration (master toggle, opt-in mode, retry policy)', 'built-in'),
    ('network:read', 'network', 'read', 'View daemon network configuration', 'built-in'),
    ('network:write', 'network', 'write', 'Update daemon network configuration (Caddy overrides, HTTP3, timeouts)', 'built-in'),
    ('pki:read', 'pki', 'read', 'View Certificate Authorities and enrollments', 'built-in'),
    ('pki:write', 'pki', 'write', 'Create CAs, trigger enrollments, revoke certificates', 'built-in'),
    ('tls:read', 'tls', 'read', 'View TLS certificates and ACME configuration', 'built-in'),
    ('tls:write', 'tls', 'write', 'Manage TLS certificates, ACME config, and cipher suites', 'built-in'),
    ('metrics:read', 'metrics', 'read', 'View metrics scrape config', 'built-in'),
    ('metrics:write', 'metrics', 'write', 'Update metrics scrape config', 'built-in'),
    ('logs:read', 'logs', 'read', 'View log levels and rotation config', 'built-in'),
    ('logs:write', 'logs', 'write', 'Update log levels and rotation config', 'built-in'),
    ('traces:read', 'traces', 'read', 'View trace retention and sampling config', 'built-in'),
    ('traces:write', 'traces', 'write', 'Update trace retention and sampling config', 'built-in'),
    ('integrations:read', 'integrations', 'read', 'View external integrations (OAuth connectors, inbound webhooks)', 'built-in'),
    ('integrations:write', 'integrations', 'write', 'Configure external integrations', 'built-in'),
    ('cluster:read', 'cluster', 'read', 'View cluster nodes and their status', 'built-in'),
    ('cluster:write', 'cluster', 'write', 'Remove cluster nodes', 'built-in'),
    ('cluster:enroll', 'cluster', 'enroll', 'Generate enrollment tokens and add new cluster members', 'built-in'),
    ('tenant:hard-reset', 'tenant', 'hard-reset', 'Hard-reset all data for the current tenant (triple-confirm)', 'built-in'),
    ('tenant:export', 'tenant', 'export', 'Export all tenant data as JSON', 'built-in'),
    ('tenant:delete', 'tenant', 'delete', 'Delete a tenant (super-admin only; triple-confirm)', 'built-in')
ON CONFLICT(id) DO NOTHING;
