/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as UnauthRouteImport } from './routes/_unauth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTenantRouteImport } from './routes/t.$tenant'
import { Route as PluginsSplatRouteImport } from './routes/plugins.$'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTenantsRouteImport } from './routes/admin/tenants'
import { Route as AdminPluginSignersRouteImport } from './routes/admin/plugin-signers'
import { Route as AdminImpersonateRouteImport } from './routes/admin/impersonate'
import { Route as AdminClusterRouteImport } from './routes/admin/cluster'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as UnauthTotpRecoveryRouteImport } from './routes/_unauth/totp-recovery'
import { Route as UnauthTotpEnrollRouteImport } from './routes/_unauth/totp-enroll'
import { Route as UnauthTotpRouteImport } from './routes/_unauth/totp'
import { Route as UnauthLoginRouteImport } from './routes/_unauth/login'
import { Route as UnauthForgotPasswordRouteImport } from './routes/_unauth/forgot-password'
import { Route as UnauthBootstrapRouteImport } from './routes/_unauth/bootstrap'
import { Route as TTenantSitesRouteImport } from './routes/t.$tenant/sites'
import { Route as TTenantSettingsRouteImport } from './routes/t.$tenant/settings'
import { Route as TTenantServicesRouteImport } from './routes/t.$tenant/services'
import { Route as TTenantSecurityRouteImport } from './routes/t.$tenant/security'
import { Route as TTenantRoutesRouteImport } from './routes/t.$tenant/routes'
import { Route as TTenantPoliciesRouteImport } from './routes/t.$tenant/policies'
import { Route as TTenantPluginsRouteImport } from './routes/t.$tenant/plugins'
import { Route as TTenantNotificationsRouteImport } from './routes/t.$tenant/notifications'
import { Route as TTenantMiddlewaresRouteImport } from './routes/t.$tenant/middlewares'
import { Route as TTenantDashboardsRouteImport } from './routes/t.$tenant/dashboards'
import { Route as TTenantDashboardRouteImport } from './routes/t.$tenant/dashboard'
import { Route as TTenantClusterRouteImport } from './routes/t.$tenant/cluster'
import { Route as TTenantApiExplorerRouteImport } from './routes/t.$tenant/api-explorer'
import { Route as TTenantAiRouteImport } from './routes/t.$tenant/ai'
import { Route as UnauthResetPasswordTokenRouteImport } from './routes/_unauth/reset-password.$token'
import { Route as UnauthInviteTokenRouteImport } from './routes/_unauth/invite.$token'
import { Route as TTenantSettingsIndexRouteImport } from './routes/t.$tenant/settings/index'
import { Route as TTenantDashboardsIndexRouteImport } from './routes/t.$tenant/dashboards.index'
import { Route as TTenantAiIndexRouteImport } from './routes/t.$tenant/ai/index'
import { Route as TTenantSettingsNotificationsRouteImport } from './routes/t.$tenant/settings/notifications'
import { Route as TTenantSettingsNotificationRoutingRouteImport } from './routes/t.$tenant/settings/notification-routing'
import { Route as TTenantSettingsNotificationDeliveryRouteImport } from './routes/t.$tenant/settings/notification-delivery'
import { Route as TTenantSettingsNotificationChannelsRouteImport } from './routes/t.$tenant/settings/notification-channels'
import { Route as TTenantSettingsAuditRetentionRouteImport } from './routes/t.$tenant/settings/audit-retention'
import { Route as TTenantSettingsUrlModeRouteImport } from './routes/t.$tenant/settings/url-mode'
import { Route as TTenantServicesServiceIdRouteImport } from './routes/t.$tenant/services_.$serviceId'
import { Route as TTenantSecurityUsersRouteImport } from './routes/t.$tenant/security/users'
import { Route as TTenantSecuritySessionsRouteImport } from './routes/t.$tenant/security/sessions'
import { Route as TTenantSecurityRolesRouteImport } from './routes/t.$tenant/security/roles'
import { Route as TTenantSecurityRbacPoliciesRouteImport } from './routes/t.$tenant/security/rbac-policies'
import { Route as TTenantSecurityAuditRouteImport } from './routes/t.$tenant/security/audit'
import { Route as TTenantSecurityApiKeysRouteImport } from './routes/t.$tenant/security/api-keys'
import { Route as TTenantSecurityAccessPoliciesRouteImport } from './routes/t.$tenant/security/access-policies'
import { Route as TTenantPluginsSignersRouteImport } from './routes/t.$tenant/plugins_.signers'
import { Route as TTenantDashboardsDashboardIdRouteImport } from './routes/t.$tenant/dashboards.$dashboardId'
import { Route as TTenantAiTracesRouteImport } from './routes/t.$tenant/ai/traces'
import { Route as TTenantAiToolsRouteImport } from './routes/t.$tenant/ai/tools'
import { Route as TTenantAiToolRoutingRouteImport } from './routes/t.$tenant/ai/tool-routing'
import { Route as TTenantAiRateLimitsRouteImport } from './routes/t.$tenant/ai/rate-limits'
import { Route as TTenantAiProvidersRouteImport } from './routes/t.$tenant/ai/providers'
import { Route as TTenantAiMcpServersRouteImport } from './routes/t.$tenant/ai/mcp-servers'
import { Route as TTenantAiAgentsRouteImport } from './routes/t.$tenant/ai/agents'
import { Route as TTenantDashboardsDashboardIdEditRouteImport } from './routes/t.$tenant/dashboards_.$dashboardId_.edit'
import { Route as TTenantDetailKindIdRouteImport } from './routes/t.$tenant/_detail.$kind.$id'

const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthRoute = UnauthRouteImport.update({
  id: '/_unauth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantRoute = TTenantRouteImport.update({
  id: '/t/$tenant',
  path: '/t/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsSplatRoute = PluginsSplatRouteImport.update({
  id: '/plugins/$',
  path: '/plugins/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPluginSignersRoute = AdminPluginSignersRouteImport.update({
  id: '/plugin-signers',
  path: '/plugin-signers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpersonateRoute = AdminImpersonateRouteImport.update({
  id: '/impersonate',
  path: '/impersonate',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClusterRoute = AdminClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const UnauthTotpRecoveryRoute = UnauthTotpRecoveryRouteImport.update({
  id: '/totp-recovery',
  path: '/totp-recovery',
  getParentRoute: () => UnauthRoute,
} as any)
const UnauthTotpEnrollRoute = UnauthTotpEnrollRouteImport.update({
  id: '/totp-enroll',
  path: '/totp-enroll',
  getParentRoute: () => UnauthRoute,
} as any)
const UnauthTotpRoute = UnauthTotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => UnauthRoute,
} as any)
const UnauthLoginRoute = UnauthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthRoute,
} as any)
const UnauthForgotPasswordRoute = UnauthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => UnauthRoute,
} as any)
const UnauthBootstrapRoute = UnauthBootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => UnauthRoute,
} as any)
const TTenantSitesRoute = TTenantSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantSettingsRoute = TTenantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantServicesRoute = TTenantServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantSecurityRoute = TTenantSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantRoutesRoute = TTenantRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantPoliciesRoute = TTenantPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantPluginsRoute = TTenantPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantNotificationsRoute = TTenantNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantMiddlewaresRoute = TTenantMiddlewaresRouteImport.update({
  id: '/middlewares',
  path: '/middlewares',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantDashboardsRoute = TTenantDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantDashboardRoute = TTenantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantClusterRoute = TTenantClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantApiExplorerRoute = TTenantApiExplorerRouteImport.update({
  id: '/api-explorer',
  path: '/api-explorer',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantAiRoute = TTenantAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => TTenantRoute,
} as any)
const UnauthResetPasswordTokenRoute =
  UnauthResetPasswordTokenRouteImport.update({
    id: '/reset-password/$token',
    path: '/reset-password/$token',
    getParentRoute: () => UnauthRoute,
  } as any)
const UnauthInviteTokenRoute = UnauthInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => UnauthRoute,
} as any)
const TTenantSettingsIndexRoute = TTenantSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTenantSettingsRoute,
} as any)
const TTenantDashboardsIndexRoute = TTenantDashboardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTenantDashboardsRoute,
} as any)
const TTenantAiIndexRoute = TTenantAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTenantAiRoute,
} as any)
const TTenantSettingsNotificationsRoute =
  TTenantSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => TTenantSettingsRoute,
  } as any)
const TTenantSettingsNotificationRoutingRoute =
  TTenantSettingsNotificationRoutingRouteImport.update({
    id: '/notification-routing',
    path: '/notification-routing',
    getParentRoute: () => TTenantSettingsRoute,
  } as any)
const TTenantSettingsNotificationDeliveryRoute =
  TTenantSettingsNotificationDeliveryRouteImport.update({
    id: '/notification-delivery',
    path: '/notification-delivery',
    getParentRoute: () => TTenantSettingsRoute,
  } as any)
const TTenantSettingsNotificationChannelsRoute =
  TTenantSettingsNotificationChannelsRouteImport.update({
    id: '/notification-channels',
    path: '/notification-channels',
    getParentRoute: () => TTenantSettingsRoute,
  } as any)
const TTenantSettingsAuditRetentionRoute =
  TTenantSettingsAuditRetentionRouteImport.update({
    id: '/audit-retention',
    path: '/audit-retention',
    getParentRoute: () => TTenantSettingsRoute,
  } as any)
const TTenantSettingsUrlModeRoute = TTenantSettingsUrlModeRouteImport.update({
  id: '/url-mode',
  path: '/url-mode',
  getParentRoute: () => TTenantSettingsRoute,
} as any)
const TTenantServicesServiceIdRoute =
  TTenantServicesServiceIdRouteImport.update({
    id: '/services_/$serviceId',
    path: '/services/$serviceId',
    getParentRoute: () => TTenantRoute,
  } as any)
const TTenantSecurityUsersRoute = TTenantSecurityUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => TTenantSecurityRoute,
} as any)
const TTenantSecuritySessionsRoute = TTenantSecuritySessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => TTenantSecurityRoute,
} as any)
const TTenantSecurityRolesRoute = TTenantSecurityRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => TTenantSecurityRoute,
} as any)
const TTenantSecurityRbacPoliciesRoute =
  TTenantSecurityRbacPoliciesRouteImport.update({
    id: '/rbac-policies',
    path: '/rbac-policies',
    getParentRoute: () => TTenantSecurityRoute,
  } as any)
const TTenantSecurityAuditRoute = TTenantSecurityAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => TTenantSecurityRoute,
} as any)
const TTenantSecurityApiKeysRoute = TTenantSecurityApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => TTenantSecurityRoute,
} as any)
const TTenantSecurityAccessPoliciesRoute =
  TTenantSecurityAccessPoliciesRouteImport.update({
    id: '/access-policies',
    path: '/access-policies',
    getParentRoute: () => TTenantSecurityRoute,
  } as any)
const TTenantPluginsSignersRoute = TTenantPluginsSignersRouteImport.update({
  id: '/plugins_/signers',
  path: '/plugins/signers',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantDashboardsDashboardIdRoute =
  TTenantDashboardsDashboardIdRouteImport.update({
    id: '/$dashboardId',
    path: '/$dashboardId',
    getParentRoute: () => TTenantDashboardsRoute,
  } as any)
const TTenantAiTracesRoute = TTenantAiTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => TTenantAiRoute,
} as any)
const TTenantAiToolsRoute = TTenantAiToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => TTenantAiRoute,
} as any)
const TTenantAiToolRoutingRoute = TTenantAiToolRoutingRouteImport.update({
  id: '/tool-routing',
  path: '/tool-routing',
  getParentRoute: () => TTenantAiRoute,
} as any)
const TTenantAiRateLimitsRoute = TTenantAiRateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => TTenantAiRoute,
} as any)
const TTenantAiProvidersRoute = TTenantAiProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => TTenantAiRoute,
} as any)
const TTenantAiMcpServersRoute = TTenantAiMcpServersRouteImport.update({
  id: '/mcp-servers',
  path: '/mcp-servers',
  getParentRoute: () => TTenantAiRoute,
} as any)
const TTenantAiAgentsRoute = TTenantAiAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => TTenantAiRoute,
} as any)
const TTenantDashboardsDashboardIdEditRoute =
  TTenantDashboardsDashboardIdEditRouteImport.update({
    id: '/dashboards_/$dashboardId_/edit',
    path: '/dashboards/$dashboardId/edit',
    getParentRoute: () => TTenantRoute,
  } as any)
const TTenantDetailKindIdRoute = TTenantDetailKindIdRouteImport.update({
  id: '/_detail/$kind/$id',
  path: '/$kind/$id',
  getParentRoute: () => TTenantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/tenants': typeof TenantsRoute
  '/bootstrap': typeof UnauthBootstrapRoute
  '/forgot-password': typeof UnauthForgotPasswordRoute
  '/login': typeof UnauthLoginRoute
  '/totp': typeof UnauthTotpRoute
  '/totp-enroll': typeof UnauthTotpEnrollRoute
  '/totp-recovery': typeof UnauthTotpRecoveryRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cluster': typeof AdminClusterRoute
  '/admin/impersonate': typeof AdminImpersonateRoute
  '/admin/plugin-signers': typeof AdminPluginSignersRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/plugins/$': typeof PluginsSplatRoute
  '/t/$tenant': typeof TTenantRouteWithChildren
  '/invite/$token': typeof UnauthInviteTokenRoute
  '/reset-password/$token': typeof UnauthResetPasswordTokenRoute
  '/t/$tenant/ai': typeof TTenantAiRouteWithChildren
  '/t/$tenant/api-explorer': typeof TTenantApiExplorerRoute
  '/t/$tenant/cluster': typeof TTenantClusterRoute
  '/t/$tenant/dashboard': typeof TTenantDashboardRoute
  '/t/$tenant/dashboards': typeof TTenantDashboardsRouteWithChildren
  '/t/$tenant/middlewares': typeof TTenantMiddlewaresRoute
  '/t/$tenant/notifications': typeof TTenantNotificationsRoute
  '/t/$tenant/plugins': typeof TTenantPluginsRoute
  '/t/$tenant/policies': typeof TTenantPoliciesRoute
  '/t/$tenant/routes': typeof TTenantRoutesRoute
  '/t/$tenant/security': typeof TTenantSecurityRouteWithChildren
  '/t/$tenant/services': typeof TTenantServicesRoute
  '/t/$tenant/settings': typeof TTenantSettingsRouteWithChildren
  '/t/$tenant/sites': typeof TTenantSitesRoute
  '/t/$tenant/ai/agents': typeof TTenantAiAgentsRoute
  '/t/$tenant/ai/mcp-servers': typeof TTenantAiMcpServersRoute
  '/t/$tenant/ai/providers': typeof TTenantAiProvidersRoute
  '/t/$tenant/ai/rate-limits': typeof TTenantAiRateLimitsRoute
  '/t/$tenant/ai/tool-routing': typeof TTenantAiToolRoutingRoute
  '/t/$tenant/ai/tools': typeof TTenantAiToolsRoute
  '/t/$tenant/ai/traces': typeof TTenantAiTracesRoute
  '/t/$tenant/dashboards/$dashboardId': typeof TTenantDashboardsDashboardIdRoute
  '/t/$tenant/plugins/signers': typeof TTenantPluginsSignersRoute
  '/t/$tenant/security/access-policies': typeof TTenantSecurityAccessPoliciesRoute
  '/t/$tenant/security/api-keys': typeof TTenantSecurityApiKeysRoute
  '/t/$tenant/security/audit': typeof TTenantSecurityAuditRoute
  '/t/$tenant/security/rbac-policies': typeof TTenantSecurityRbacPoliciesRoute
  '/t/$tenant/security/roles': typeof TTenantSecurityRolesRoute
  '/t/$tenant/security/sessions': typeof TTenantSecuritySessionsRoute
  '/t/$tenant/security/users': typeof TTenantSecurityUsersRoute
  '/t/$tenant/services/$serviceId': typeof TTenantServicesServiceIdRoute
  '/t/$tenant/settings/audit-retention': typeof TTenantSettingsAuditRetentionRoute
  '/t/$tenant/settings/url-mode': typeof TTenantSettingsUrlModeRoute
  '/t/$tenant/settings/notification-channels': typeof TTenantSettingsNotificationChannelsRoute
  '/t/$tenant/settings/notification-delivery': typeof TTenantSettingsNotificationDeliveryRoute
  '/t/$tenant/settings/notification-routing': typeof TTenantSettingsNotificationRoutingRoute
  '/t/$tenant/settings/notifications': typeof TTenantSettingsNotificationsRoute
  '/t/$tenant/ai/': typeof TTenantAiIndexRoute
  '/t/$tenant/dashboards/': typeof TTenantDashboardsIndexRoute
  '/t/$tenant/settings/': typeof TTenantSettingsIndexRoute
  '/t/$tenant/$kind/$id': typeof TTenantDetailKindIdRoute
  '/t/$tenant/dashboards/$dashboardId/edit': typeof TTenantDashboardsDashboardIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/tenants': typeof TenantsRoute
  '/bootstrap': typeof UnauthBootstrapRoute
  '/forgot-password': typeof UnauthForgotPasswordRoute
  '/login': typeof UnauthLoginRoute
  '/totp': typeof UnauthTotpRoute
  '/totp-enroll': typeof UnauthTotpEnrollRoute
  '/totp-recovery': typeof UnauthTotpRecoveryRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cluster': typeof AdminClusterRoute
  '/admin/impersonate': typeof AdminImpersonateRoute
  '/admin/plugin-signers': typeof AdminPluginSignersRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/plugins/$': typeof PluginsSplatRoute
  '/t/$tenant': typeof TTenantRouteWithChildren
  '/invite/$token': typeof UnauthInviteTokenRoute
  '/reset-password/$token': typeof UnauthResetPasswordTokenRoute
  '/t/$tenant/api-explorer': typeof TTenantApiExplorerRoute
  '/t/$tenant/cluster': typeof TTenantClusterRoute
  '/t/$tenant/dashboard': typeof TTenantDashboardRoute
  '/t/$tenant/middlewares': typeof TTenantMiddlewaresRoute
  '/t/$tenant/notifications': typeof TTenantNotificationsRoute
  '/t/$tenant/plugins': typeof TTenantPluginsRoute
  '/t/$tenant/policies': typeof TTenantPoliciesRoute
  '/t/$tenant/routes': typeof TTenantRoutesRoute
  '/t/$tenant/security': typeof TTenantSecurityRouteWithChildren
  '/t/$tenant/services': typeof TTenantServicesRoute
  '/t/$tenant/sites': typeof TTenantSitesRoute
  '/t/$tenant/ai/agents': typeof TTenantAiAgentsRoute
  '/t/$tenant/ai/mcp-servers': typeof TTenantAiMcpServersRoute
  '/t/$tenant/ai/providers': typeof TTenantAiProvidersRoute
  '/t/$tenant/ai/rate-limits': typeof TTenantAiRateLimitsRoute
  '/t/$tenant/ai/tool-routing': typeof TTenantAiToolRoutingRoute
  '/t/$tenant/ai/tools': typeof TTenantAiToolsRoute
  '/t/$tenant/ai/traces': typeof TTenantAiTracesRoute
  '/t/$tenant/dashboards/$dashboardId': typeof TTenantDashboardsDashboardIdRoute
  '/t/$tenant/plugins/signers': typeof TTenantPluginsSignersRoute
  '/t/$tenant/security/access-policies': typeof TTenantSecurityAccessPoliciesRoute
  '/t/$tenant/security/api-keys': typeof TTenantSecurityApiKeysRoute
  '/t/$tenant/security/audit': typeof TTenantSecurityAuditRoute
  '/t/$tenant/security/rbac-policies': typeof TTenantSecurityRbacPoliciesRoute
  '/t/$tenant/security/roles': typeof TTenantSecurityRolesRoute
  '/t/$tenant/security/sessions': typeof TTenantSecuritySessionsRoute
  '/t/$tenant/security/users': typeof TTenantSecurityUsersRoute
  '/t/$tenant/services/$serviceId': typeof TTenantServicesServiceIdRoute
  '/t/$tenant/settings/audit-retention': typeof TTenantSettingsAuditRetentionRoute
  '/t/$tenant/settings/url-mode': typeof TTenantSettingsUrlModeRoute
  '/t/$tenant/settings/notification-channels': typeof TTenantSettingsNotificationChannelsRoute
  '/t/$tenant/settings/notification-delivery': typeof TTenantSettingsNotificationDeliveryRoute
  '/t/$tenant/settings/notification-routing': typeof TTenantSettingsNotificationRoutingRoute
  '/t/$tenant/settings/notifications': typeof TTenantSettingsNotificationsRoute
  '/t/$tenant/ai': typeof TTenantAiIndexRoute
  '/t/$tenant/dashboards': typeof TTenantDashboardsIndexRoute
  '/t/$tenant/settings': typeof TTenantSettingsIndexRoute
  '/t/$tenant/$kind/$id': typeof TTenantDetailKindIdRoute
  '/t/$tenant/dashboards/$dashboardId/edit': typeof TTenantDashboardsDashboardIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_unauth': typeof UnauthRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/tenants': typeof TenantsRoute
  '/_unauth/bootstrap': typeof UnauthBootstrapRoute
  '/_unauth/forgot-password': typeof UnauthForgotPasswordRoute
  '/_unauth/login': typeof UnauthLoginRoute
  '/_unauth/totp': typeof UnauthTotpRoute
  '/_unauth/totp-enroll': typeof UnauthTotpEnrollRoute
  '/_unauth/totp-recovery': typeof UnauthTotpRecoveryRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cluster': typeof AdminClusterRoute
  '/admin/impersonate': typeof AdminImpersonateRoute
  '/admin/plugin-signers': typeof AdminPluginSignersRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/plugins/$': typeof PluginsSplatRoute
  '/t/$tenant': typeof TTenantRouteWithChildren
  '/_unauth/invite/$token': typeof UnauthInviteTokenRoute
  '/_unauth/reset-password/$token': typeof UnauthResetPasswordTokenRoute
  '/t/$tenant/ai': typeof TTenantAiRouteWithChildren
  '/t/$tenant/api-explorer': typeof TTenantApiExplorerRoute
  '/t/$tenant/cluster': typeof TTenantClusterRoute
  '/t/$tenant/dashboard': typeof TTenantDashboardRoute
  '/t/$tenant/dashboards': typeof TTenantDashboardsRouteWithChildren
  '/t/$tenant/middlewares': typeof TTenantMiddlewaresRoute
  '/t/$tenant/notifications': typeof TTenantNotificationsRoute
  '/t/$tenant/plugins': typeof TTenantPluginsRoute
  '/t/$tenant/policies': typeof TTenantPoliciesRoute
  '/t/$tenant/routes': typeof TTenantRoutesRoute
  '/t/$tenant/security': typeof TTenantSecurityRouteWithChildren
  '/t/$tenant/services': typeof TTenantServicesRoute
  '/t/$tenant/settings': typeof TTenantSettingsRouteWithChildren
  '/t/$tenant/sites': typeof TTenantSitesRoute
  '/t/$tenant/ai/agents': typeof TTenantAiAgentsRoute
  '/t/$tenant/ai/mcp-servers': typeof TTenantAiMcpServersRoute
  '/t/$tenant/ai/providers': typeof TTenantAiProvidersRoute
  '/t/$tenant/ai/rate-limits': typeof TTenantAiRateLimitsRoute
  '/t/$tenant/ai/tool-routing': typeof TTenantAiToolRoutingRoute
  '/t/$tenant/ai/tools': typeof TTenantAiToolsRoute
  '/t/$tenant/ai/traces': typeof TTenantAiTracesRoute
  '/t/$tenant/dashboards/$dashboardId': typeof TTenantDashboardsDashboardIdRoute
  '/t/$tenant/plugins_/signers': typeof TTenantPluginsSignersRoute
  '/t/$tenant/security/access-policies': typeof TTenantSecurityAccessPoliciesRoute
  '/t/$tenant/security/api-keys': typeof TTenantSecurityApiKeysRoute
  '/t/$tenant/security/audit': typeof TTenantSecurityAuditRoute
  '/t/$tenant/security/rbac-policies': typeof TTenantSecurityRbacPoliciesRoute
  '/t/$tenant/security/roles': typeof TTenantSecurityRolesRoute
  '/t/$tenant/security/sessions': typeof TTenantSecuritySessionsRoute
  '/t/$tenant/security/users': typeof TTenantSecurityUsersRoute
  '/t/$tenant/services_/$serviceId': typeof TTenantServicesServiceIdRoute
  '/t/$tenant/settings/audit-retention': typeof TTenantSettingsAuditRetentionRoute
  '/t/$tenant/settings/url-mode': typeof TTenantSettingsUrlModeRoute
  '/t/$tenant/settings/notification-channels': typeof TTenantSettingsNotificationChannelsRoute
  '/t/$tenant/settings/notification-delivery': typeof TTenantSettingsNotificationDeliveryRoute
  '/t/$tenant/settings/notification-routing': typeof TTenantSettingsNotificationRoutingRoute
  '/t/$tenant/settings/notifications': typeof TTenantSettingsNotificationsRoute
  '/t/$tenant/ai/': typeof TTenantAiIndexRoute
  '/t/$tenant/dashboards/': typeof TTenantDashboardsIndexRoute
  '/t/$tenant/settings/': typeof TTenantSettingsIndexRoute
  '/t/$tenant/_detail/$kind/$id': typeof TTenantDetailKindIdRoute
  '/t/$tenant/dashboards_/$dashboardId_/edit': typeof TTenantDashboardsDashboardIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/admin'
    | '/tenants'
    | '/bootstrap'
    | '/forgot-password'
    | '/login'
    | '/totp'
    | '/totp-enroll'
    | '/totp-recovery'
    | '/admin/audit'
    | '/admin/cluster'
    | '/admin/impersonate'
    | '/admin/plugin-signers'
    | '/admin/tenants'
    | '/admin/users'
    | '/plugins/$'
    | '/t/$tenant'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/t/$tenant/ai'
    | '/t/$tenant/api-explorer'
    | '/t/$tenant/cluster'
    | '/t/$tenant/dashboard'
    | '/t/$tenant/dashboards'
    | '/t/$tenant/middlewares'
    | '/t/$tenant/notifications'
    | '/t/$tenant/plugins'
    | '/t/$tenant/policies'
    | '/t/$tenant/routes'
    | '/t/$tenant/security'
    | '/t/$tenant/services'
    | '/t/$tenant/settings'
    | '/t/$tenant/sites'
    | '/t/$tenant/ai/agents'
    | '/t/$tenant/ai/mcp-servers'
    | '/t/$tenant/ai/providers'
    | '/t/$tenant/ai/rate-limits'
    | '/t/$tenant/ai/tool-routing'
    | '/t/$tenant/ai/tools'
    | '/t/$tenant/ai/traces'
    | '/t/$tenant/dashboards/$dashboardId'
    | '/t/$tenant/plugins/signers'
    | '/t/$tenant/security/access-policies'
    | '/t/$tenant/security/api-keys'
    | '/t/$tenant/security/audit'
    | '/t/$tenant/security/rbac-policies'
    | '/t/$tenant/security/roles'
    | '/t/$tenant/security/sessions'
    | '/t/$tenant/security/users'
    | '/t/$tenant/services/$serviceId'
    | '/t/$tenant/settings/audit-retention'
    | '/t/$tenant/settings/url-mode'
    | '/t/$tenant/settings/notification-channels'
    | '/t/$tenant/settings/notification-delivery'
    | '/t/$tenant/settings/notification-routing'
    | '/t/$tenant/settings/notifications'
    | '/t/$tenant/ai/'
    | '/t/$tenant/dashboards/'
    | '/t/$tenant/settings/'
    | '/t/$tenant/$kind/$id'
    | '/t/$tenant/dashboards/$dashboardId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/admin'
    | '/tenants'
    | '/bootstrap'
    | '/forgot-password'
    | '/login'
    | '/totp'
    | '/totp-enroll'
    | '/totp-recovery'
    | '/admin/audit'
    | '/admin/cluster'
    | '/admin/impersonate'
    | '/admin/plugin-signers'
    | '/admin/tenants'
    | '/admin/users'
    | '/plugins/$'
    | '/t/$tenant'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/t/$tenant/api-explorer'
    | '/t/$tenant/cluster'
    | '/t/$tenant/dashboard'
    | '/t/$tenant/middlewares'
    | '/t/$tenant/notifications'
    | '/t/$tenant/plugins'
    | '/t/$tenant/policies'
    | '/t/$tenant/routes'
    | '/t/$tenant/security'
    | '/t/$tenant/services'
    | '/t/$tenant/sites'
    | '/t/$tenant/ai/agents'
    | '/t/$tenant/ai/mcp-servers'
    | '/t/$tenant/ai/providers'
    | '/t/$tenant/ai/rate-limits'
    | '/t/$tenant/ai/tool-routing'
    | '/t/$tenant/ai/tools'
    | '/t/$tenant/ai/traces'
    | '/t/$tenant/dashboards/$dashboardId'
    | '/t/$tenant/plugins/signers'
    | '/t/$tenant/security/access-policies'
    | '/t/$tenant/security/api-keys'
    | '/t/$tenant/security/audit'
    | '/t/$tenant/security/rbac-policies'
    | '/t/$tenant/security/roles'
    | '/t/$tenant/security/sessions'
    | '/t/$tenant/security/users'
    | '/t/$tenant/services/$serviceId'
    | '/t/$tenant/settings/audit-retention'
    | '/t/$tenant/settings/url-mode'
    | '/t/$tenant/settings/notification-channels'
    | '/t/$tenant/settings/notification-delivery'
    | '/t/$tenant/settings/notification-routing'
    | '/t/$tenant/settings/notifications'
    | '/t/$tenant/ai'
    | '/t/$tenant/dashboards'
    | '/t/$tenant/settings'
    | '/t/$tenant/$kind/$id'
    | '/t/$tenant/dashboards/$dashboardId/edit'
  id:
    | '__root__'
    | '/'
    | '/_unauth'
    | '/access-denied'
    | '/admin'
    | '/tenants'
    | '/_unauth/bootstrap'
    | '/_unauth/forgot-password'
    | '/_unauth/login'
    | '/_unauth/totp'
    | '/_unauth/totp-enroll'
    | '/_unauth/totp-recovery'
    | '/admin/audit'
    | '/admin/cluster'
    | '/admin/impersonate'
    | '/admin/plugin-signers'
    | '/admin/tenants'
    | '/admin/users'
    | '/plugins/$'
    | '/t/$tenant'
    | '/_unauth/invite/$token'
    | '/_unauth/reset-password/$token'
    | '/t/$tenant/ai'
    | '/t/$tenant/api-explorer'
    | '/t/$tenant/cluster'
    | '/t/$tenant/dashboard'
    | '/t/$tenant/dashboards'
    | '/t/$tenant/middlewares'
    | '/t/$tenant/notifications'
    | '/t/$tenant/plugins'
    | '/t/$tenant/policies'
    | '/t/$tenant/routes'
    | '/t/$tenant/security'
    | '/t/$tenant/services'
    | '/t/$tenant/settings'
    | '/t/$tenant/sites'
    | '/t/$tenant/ai/agents'
    | '/t/$tenant/ai/mcp-servers'
    | '/t/$tenant/ai/providers'
    | '/t/$tenant/ai/rate-limits'
    | '/t/$tenant/ai/tool-routing'
    | '/t/$tenant/ai/tools'
    | '/t/$tenant/ai/traces'
    | '/t/$tenant/dashboards/$dashboardId'
    | '/t/$tenant/plugins_/signers'
    | '/t/$tenant/security/access-policies'
    | '/t/$tenant/security/api-keys'
    | '/t/$tenant/security/audit'
    | '/t/$tenant/security/rbac-policies'
    | '/t/$tenant/security/roles'
    | '/t/$tenant/security/sessions'
    | '/t/$tenant/security/users'
    | '/t/$tenant/services_/$serviceId'
    | '/t/$tenant/settings/audit-retention'
    | '/t/$tenant/settings/url-mode'
    | '/t/$tenant/settings/notification-channels'
    | '/t/$tenant/settings/notification-delivery'
    | '/t/$tenant/settings/notification-routing'
    | '/t/$tenant/settings/notifications'
    | '/t/$tenant/ai/'
    | '/t/$tenant/dashboards/'
    | '/t/$tenant/settings/'
    | '/t/$tenant/_detail/$kind/$id'
    | '/t/$tenant/dashboards_/$dashboardId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UnauthRoute: typeof UnauthRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  AdminRoute: typeof AdminRouteWithChildren
  TenantsRoute: typeof TenantsRoute
  PluginsSplatRoute: typeof PluginsSplatRoute
  TTenantRoute: typeof TTenantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauth': {
      id: '/_unauth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenant': {
      id: '/t/$tenant'
      path: '/t/$tenant'
      fullPath: '/t/$tenant'
      preLoaderRoute: typeof TTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$': {
      id: '/plugins/$'
      path: '/plugins/$'
      fullPath: '/plugins/$'
      preLoaderRoute: typeof PluginsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plugin-signers': {
      id: '/admin/plugin-signers'
      path: '/plugin-signers'
      fullPath: '/admin/plugin-signers'
      preLoaderRoute: typeof AdminPluginSignersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impersonate': {
      id: '/admin/impersonate'
      path: '/impersonate'
      fullPath: '/admin/impersonate'
      preLoaderRoute: typeof AdminImpersonateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cluster': {
      id: '/admin/cluster'
      path: '/cluster'
      fullPath: '/admin/cluster'
      preLoaderRoute: typeof AdminClusterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_unauth/totp-recovery': {
      id: '/_unauth/totp-recovery'
      path: '/totp-recovery'
      fullPath: '/totp-recovery'
      preLoaderRoute: typeof UnauthTotpRecoveryRouteImport
      parentRoute: typeof UnauthRoute
    }
    '/_unauth/totp-enroll': {
      id: '/_unauth/totp-enroll'
      path: '/totp-enroll'
      fullPath: '/totp-enroll'
      preLoaderRoute: typeof UnauthTotpEnrollRouteImport
      parentRoute: typeof UnauthRoute
    }
    '/_unauth/totp': {
      id: '/_unauth/totp'
      path: '/totp'
      fullPath: '/totp'
      preLoaderRoute: typeof UnauthTotpRouteImport
      parentRoute: typeof UnauthRoute
    }
    '/_unauth/login': {
      id: '/_unauth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthLoginRouteImport
      parentRoute: typeof UnauthRoute
    }
    '/_unauth/forgot-password': {
      id: '/_unauth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof UnauthForgotPasswordRouteImport
      parentRoute: typeof UnauthRoute
    }
    '/_unauth/bootstrap': {
      id: '/_unauth/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof UnauthBootstrapRouteImport
      parentRoute: typeof UnauthRoute
    }
    '/t/$tenant/sites': {
      id: '/t/$tenant/sites'
      path: '/sites'
      fullPath: '/t/$tenant/sites'
      preLoaderRoute: typeof TTenantSitesRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/settings': {
      id: '/t/$tenant/settings'
      path: '/settings'
      fullPath: '/t/$tenant/settings'
      preLoaderRoute: typeof TTenantSettingsRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/services': {
      id: '/t/$tenant/services'
      path: '/services'
      fullPath: '/t/$tenant/services'
      preLoaderRoute: typeof TTenantServicesRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/security': {
      id: '/t/$tenant/security'
      path: '/security'
      fullPath: '/t/$tenant/security'
      preLoaderRoute: typeof TTenantSecurityRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/routes': {
      id: '/t/$tenant/routes'
      path: '/routes'
      fullPath: '/t/$tenant/routes'
      preLoaderRoute: typeof TTenantRoutesRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/policies': {
      id: '/t/$tenant/policies'
      path: '/policies'
      fullPath: '/t/$tenant/policies'
      preLoaderRoute: typeof TTenantPoliciesRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/plugins': {
      id: '/t/$tenant/plugins'
      path: '/plugins'
      fullPath: '/t/$tenant/plugins'
      preLoaderRoute: typeof TTenantPluginsRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/notifications': {
      id: '/t/$tenant/notifications'
      path: '/notifications'
      fullPath: '/t/$tenant/notifications'
      preLoaderRoute: typeof TTenantNotificationsRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/middlewares': {
      id: '/t/$tenant/middlewares'
      path: '/middlewares'
      fullPath: '/t/$tenant/middlewares'
      preLoaderRoute: typeof TTenantMiddlewaresRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/dashboards': {
      id: '/t/$tenant/dashboards'
      path: '/dashboards'
      fullPath: '/t/$tenant/dashboards'
      preLoaderRoute: typeof TTenantDashboardsRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/dashboard': {
      id: '/t/$tenant/dashboard'
      path: '/dashboard'
      fullPath: '/t/$tenant/dashboard'
      preLoaderRoute: typeof TTenantDashboardRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/cluster': {
      id: '/t/$tenant/cluster'
      path: '/cluster'
      fullPath: '/t/$tenant/cluster'
      preLoaderRoute: typeof TTenantClusterRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/api-explorer': {
      id: '/t/$tenant/api-explorer'
      path: '/api-explorer'
      fullPath: '/t/$tenant/api-explorer'
      preLoaderRoute: typeof TTenantApiExplorerRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/ai': {
      id: '/t/$tenant/ai'
      path: '/ai'
      fullPath: '/t/$tenant/ai'
      preLoaderRoute: typeof TTenantAiRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/_unauth/reset-password/$token': {
      id: '/_unauth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof UnauthResetPasswordTokenRouteImport
      parentRoute: typeof UnauthRoute
    }
    '/_unauth/invite/$token': {
      id: '/_unauth/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof UnauthInviteTokenRouteImport
      parentRoute: typeof UnauthRoute
    }
    '/t/$tenant/settings/': {
      id: '/t/$tenant/settings/'
      path: '/'
      fullPath: '/t/$tenant/settings/'
      preLoaderRoute: typeof TTenantSettingsIndexRouteImport
      parentRoute: typeof TTenantSettingsRoute
    }
    '/t/$tenant/dashboards/': {
      id: '/t/$tenant/dashboards/'
      path: '/'
      fullPath: '/t/$tenant/dashboards/'
      preLoaderRoute: typeof TTenantDashboardsIndexRouteImport
      parentRoute: typeof TTenantDashboardsRoute
    }
    '/t/$tenant/ai/': {
      id: '/t/$tenant/ai/'
      path: '/'
      fullPath: '/t/$tenant/ai/'
      preLoaderRoute: typeof TTenantAiIndexRouteImport
      parentRoute: typeof TTenantAiRoute
    }
    '/t/$tenant/settings/notifications': {
      id: '/t/$tenant/settings/notifications'
      path: '/notifications'
      fullPath: '/t/$tenant/settings/notifications'
      preLoaderRoute: typeof TTenantSettingsNotificationsRouteImport
      parentRoute: typeof TTenantSettingsRoute
    }
    '/t/$tenant/settings/notification-routing': {
      id: '/t/$tenant/settings/notification-routing'
      path: '/notification-routing'
      fullPath: '/t/$tenant/settings/notification-routing'
      preLoaderRoute: typeof TTenantSettingsNotificationRoutingRouteImport
      parentRoute: typeof TTenantSettingsRoute
    }
    '/t/$tenant/settings/notification-delivery': {
      id: '/t/$tenant/settings/notification-delivery'
      path: '/notification-delivery'
      fullPath: '/t/$tenant/settings/notification-delivery'
      preLoaderRoute: typeof TTenantSettingsNotificationDeliveryRouteImport
      parentRoute: typeof TTenantSettingsRoute
    }
    '/t/$tenant/settings/notification-channels': {
      id: '/t/$tenant/settings/notification-channels'
      path: '/notification-channels'
      fullPath: '/t/$tenant/settings/notification-channels'
      preLoaderRoute: typeof TTenantSettingsNotificationChannelsRouteImport
      parentRoute: typeof TTenantSettingsRoute
    }
    '/t/$tenant/settings/audit-retention': {
      id: '/t/$tenant/settings/audit-retention'
      path: '/audit-retention'
      fullPath: '/t/$tenant/settings/audit-retention'
      preLoaderRoute: typeof TTenantSettingsAuditRetentionRouteImport
      parentRoute: typeof TTenantSettingsRoute
    }
    '/t/$tenant/settings/url-mode': {
      id: '/t/$tenant/settings/url-mode'
      path: '/url-mode'
      fullPath: '/t/$tenant/settings/url-mode'
      preLoaderRoute: typeof TTenantSettingsUrlModeRouteImport
      parentRoute: typeof TTenantSettingsRoute
    }
    '/t/$tenant/services_/$serviceId': {
      id: '/t/$tenant/services_/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/t/$tenant/services/$serviceId'
      preLoaderRoute: typeof TTenantServicesServiceIdRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/security/users': {
      id: '/t/$tenant/security/users'
      path: '/users'
      fullPath: '/t/$tenant/security/users'
      preLoaderRoute: typeof TTenantSecurityUsersRouteImport
      parentRoute: typeof TTenantSecurityRoute
    }
    '/t/$tenant/security/sessions': {
      id: '/t/$tenant/security/sessions'
      path: '/sessions'
      fullPath: '/t/$tenant/security/sessions'
      preLoaderRoute: typeof TTenantSecuritySessionsRouteImport
      parentRoute: typeof TTenantSecurityRoute
    }
    '/t/$tenant/security/roles': {
      id: '/t/$tenant/security/roles'
      path: '/roles'
      fullPath: '/t/$tenant/security/roles'
      preLoaderRoute: typeof TTenantSecurityRolesRouteImport
      parentRoute: typeof TTenantSecurityRoute
    }
    '/t/$tenant/security/rbac-policies': {
      id: '/t/$tenant/security/rbac-policies'
      path: '/rbac-policies'
      fullPath: '/t/$tenant/security/rbac-policies'
      preLoaderRoute: typeof TTenantSecurityRbacPoliciesRouteImport
      parentRoute: typeof TTenantSecurityRoute
    }
    '/t/$tenant/security/audit': {
      id: '/t/$tenant/security/audit'
      path: '/audit'
      fullPath: '/t/$tenant/security/audit'
      preLoaderRoute: typeof TTenantSecurityAuditRouteImport
      parentRoute: typeof TTenantSecurityRoute
    }
    '/t/$tenant/security/api-keys': {
      id: '/t/$tenant/security/api-keys'
      path: '/api-keys'
      fullPath: '/t/$tenant/security/api-keys'
      preLoaderRoute: typeof TTenantSecurityApiKeysRouteImport
      parentRoute: typeof TTenantSecurityRoute
    }
    '/t/$tenant/security/access-policies': {
      id: '/t/$tenant/security/access-policies'
      path: '/access-policies'
      fullPath: '/t/$tenant/security/access-policies'
      preLoaderRoute: typeof TTenantSecurityAccessPoliciesRouteImport
      parentRoute: typeof TTenantSecurityRoute
    }
    '/t/$tenant/plugins_/signers': {
      id: '/t/$tenant/plugins_/signers'
      path: '/plugins/signers'
      fullPath: '/t/$tenant/plugins/signers'
      preLoaderRoute: typeof TTenantPluginsSignersRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/dashboards/$dashboardId': {
      id: '/t/$tenant/dashboards/$dashboardId'
      path: '/$dashboardId'
      fullPath: '/t/$tenant/dashboards/$dashboardId'
      preLoaderRoute: typeof TTenantDashboardsDashboardIdRouteImport
      parentRoute: typeof TTenantDashboardsRoute
    }
    '/t/$tenant/ai/traces': {
      id: '/t/$tenant/ai/traces'
      path: '/traces'
      fullPath: '/t/$tenant/ai/traces'
      preLoaderRoute: typeof TTenantAiTracesRouteImport
      parentRoute: typeof TTenantAiRoute
    }
    '/t/$tenant/ai/tools': {
      id: '/t/$tenant/ai/tools'
      path: '/tools'
      fullPath: '/t/$tenant/ai/tools'
      preLoaderRoute: typeof TTenantAiToolsRouteImport
      parentRoute: typeof TTenantAiRoute
    }
    '/t/$tenant/ai/tool-routing': {
      id: '/t/$tenant/ai/tool-routing'
      path: '/tool-routing'
      fullPath: '/t/$tenant/ai/tool-routing'
      preLoaderRoute: typeof TTenantAiToolRoutingRouteImport
      parentRoute: typeof TTenantAiRoute
    }
    '/t/$tenant/ai/rate-limits': {
      id: '/t/$tenant/ai/rate-limits'
      path: '/rate-limits'
      fullPath: '/t/$tenant/ai/rate-limits'
      preLoaderRoute: typeof TTenantAiRateLimitsRouteImport
      parentRoute: typeof TTenantAiRoute
    }
    '/t/$tenant/ai/providers': {
      id: '/t/$tenant/ai/providers'
      path: '/providers'
      fullPath: '/t/$tenant/ai/providers'
      preLoaderRoute: typeof TTenantAiProvidersRouteImport
      parentRoute: typeof TTenantAiRoute
    }
    '/t/$tenant/ai/mcp-servers': {
      id: '/t/$tenant/ai/mcp-servers'
      path: '/mcp-servers'
      fullPath: '/t/$tenant/ai/mcp-servers'
      preLoaderRoute: typeof TTenantAiMcpServersRouteImport
      parentRoute: typeof TTenantAiRoute
    }
    '/t/$tenant/ai/agents': {
      id: '/t/$tenant/ai/agents'
      path: '/agents'
      fullPath: '/t/$tenant/ai/agents'
      preLoaderRoute: typeof TTenantAiAgentsRouteImport
      parentRoute: typeof TTenantAiRoute
    }
    '/t/$tenant/dashboards_/$dashboardId_/edit': {
      id: '/t/$tenant/dashboards_/$dashboardId_/edit'
      path: '/dashboards/$dashboardId/edit'
      fullPath: '/t/$tenant/dashboards/$dashboardId/edit'
      preLoaderRoute: typeof TTenantDashboardsDashboardIdEditRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/_detail/$kind/$id': {
      id: '/t/$tenant/_detail/$kind/$id'
      path: '/$kind/$id'
      fullPath: '/t/$tenant/$kind/$id'
      preLoaderRoute: typeof TTenantDetailKindIdRouteImport
      parentRoute: typeof TTenantRoute
    }
  }
}

interface UnauthRouteChildren {
  UnauthBootstrapRoute: typeof UnauthBootstrapRoute
  UnauthForgotPasswordRoute: typeof UnauthForgotPasswordRoute
  UnauthLoginRoute: typeof UnauthLoginRoute
  UnauthTotpRoute: typeof UnauthTotpRoute
  UnauthTotpEnrollRoute: typeof UnauthTotpEnrollRoute
  UnauthTotpRecoveryRoute: typeof UnauthTotpRecoveryRoute
  UnauthInviteTokenRoute: typeof UnauthInviteTokenRoute
  UnauthResetPasswordTokenRoute: typeof UnauthResetPasswordTokenRoute
}

const UnauthRouteChildren: UnauthRouteChildren = {
  UnauthBootstrapRoute: UnauthBootstrapRoute,
  UnauthForgotPasswordRoute: UnauthForgotPasswordRoute,
  UnauthLoginRoute: UnauthLoginRoute,
  UnauthTotpRoute: UnauthTotpRoute,
  UnauthTotpEnrollRoute: UnauthTotpEnrollRoute,
  UnauthTotpRecoveryRoute: UnauthTotpRecoveryRoute,
  UnauthInviteTokenRoute: UnauthInviteTokenRoute,
  UnauthResetPasswordTokenRoute: UnauthResetPasswordTokenRoute,
}

const UnauthRouteWithChildren =
  UnauthRoute._addFileChildren(UnauthRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminClusterRoute: typeof AdminClusterRoute
  AdminImpersonateRoute: typeof AdminImpersonateRoute
  AdminPluginSignersRoute: typeof AdminPluginSignersRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminClusterRoute: AdminClusterRoute,
  AdminImpersonateRoute: AdminImpersonateRoute,
  AdminPluginSignersRoute: AdminPluginSignersRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TTenantAiRouteChildren {
  TTenantAiAgentsRoute: typeof TTenantAiAgentsRoute
  TTenantAiMcpServersRoute: typeof TTenantAiMcpServersRoute
  TTenantAiProvidersRoute: typeof TTenantAiProvidersRoute
  TTenantAiRateLimitsRoute: typeof TTenantAiRateLimitsRoute
  TTenantAiToolRoutingRoute: typeof TTenantAiToolRoutingRoute
  TTenantAiToolsRoute: typeof TTenantAiToolsRoute
  TTenantAiTracesRoute: typeof TTenantAiTracesRoute
  TTenantAiIndexRoute: typeof TTenantAiIndexRoute
}

const TTenantAiRouteChildren: TTenantAiRouteChildren = {
  TTenantAiAgentsRoute: TTenantAiAgentsRoute,
  TTenantAiMcpServersRoute: TTenantAiMcpServersRoute,
  TTenantAiProvidersRoute: TTenantAiProvidersRoute,
  TTenantAiRateLimitsRoute: TTenantAiRateLimitsRoute,
  TTenantAiToolRoutingRoute: TTenantAiToolRoutingRoute,
  TTenantAiToolsRoute: TTenantAiToolsRoute,
  TTenantAiTracesRoute: TTenantAiTracesRoute,
  TTenantAiIndexRoute: TTenantAiIndexRoute,
}

const TTenantAiRouteWithChildren = TTenantAiRoute._addFileChildren(
  TTenantAiRouteChildren,
)

interface TTenantDashboardsRouteChildren {
  TTenantDashboardsDashboardIdRoute: typeof TTenantDashboardsDashboardIdRoute
  TTenantDashboardsIndexRoute: typeof TTenantDashboardsIndexRoute
}

const TTenantDashboardsRouteChildren: TTenantDashboardsRouteChildren = {
  TTenantDashboardsDashboardIdRoute: TTenantDashboardsDashboardIdRoute,
  TTenantDashboardsIndexRoute: TTenantDashboardsIndexRoute,
}

const TTenantDashboardsRouteWithChildren =
  TTenantDashboardsRoute._addFileChildren(TTenantDashboardsRouteChildren)

interface TTenantSecurityRouteChildren {
  TTenantSecurityAccessPoliciesRoute: typeof TTenantSecurityAccessPoliciesRoute
  TTenantSecurityApiKeysRoute: typeof TTenantSecurityApiKeysRoute
  TTenantSecurityAuditRoute: typeof TTenantSecurityAuditRoute
  TTenantSecurityRbacPoliciesRoute: typeof TTenantSecurityRbacPoliciesRoute
  TTenantSecurityRolesRoute: typeof TTenantSecurityRolesRoute
  TTenantSecuritySessionsRoute: typeof TTenantSecuritySessionsRoute
  TTenantSecurityUsersRoute: typeof TTenantSecurityUsersRoute
}

const TTenantSecurityRouteChildren: TTenantSecurityRouteChildren = {
  TTenantSecurityAccessPoliciesRoute: TTenantSecurityAccessPoliciesRoute,
  TTenantSecurityApiKeysRoute: TTenantSecurityApiKeysRoute,
  TTenantSecurityAuditRoute: TTenantSecurityAuditRoute,
  TTenantSecurityRbacPoliciesRoute: TTenantSecurityRbacPoliciesRoute,
  TTenantSecurityRolesRoute: TTenantSecurityRolesRoute,
  TTenantSecuritySessionsRoute: TTenantSecuritySessionsRoute,
  TTenantSecurityUsersRoute: TTenantSecurityUsersRoute,
}

const TTenantSecurityRouteWithChildren = TTenantSecurityRoute._addFileChildren(
  TTenantSecurityRouteChildren,
)

interface TTenantSettingsRouteChildren {
  TTenantSettingsAuditRetentionRoute: typeof TTenantSettingsAuditRetentionRoute
  TTenantSettingsUrlModeRoute: typeof TTenantSettingsUrlModeRoute
  TTenantSettingsNotificationChannelsRoute: typeof TTenantSettingsNotificationChannelsRoute
  TTenantSettingsNotificationDeliveryRoute: typeof TTenantSettingsNotificationDeliveryRoute
  TTenantSettingsNotificationRoutingRoute: typeof TTenantSettingsNotificationRoutingRoute
  TTenantSettingsNotificationsRoute: typeof TTenantSettingsNotificationsRoute
  TTenantSettingsIndexRoute: typeof TTenantSettingsIndexRoute
}

const TTenantSettingsRouteChildren: TTenantSettingsRouteChildren = {
  TTenantSettingsAuditRetentionRoute: TTenantSettingsAuditRetentionRoute,
  TTenantSettingsUrlModeRoute: TTenantSettingsUrlModeRoute,
  TTenantSettingsNotificationChannelsRoute:
    TTenantSettingsNotificationChannelsRoute,
  TTenantSettingsNotificationDeliveryRoute:
    TTenantSettingsNotificationDeliveryRoute,
  TTenantSettingsNotificationRoutingRoute:
    TTenantSettingsNotificationRoutingRoute,
  TTenantSettingsNotificationsRoute: TTenantSettingsNotificationsRoute,
  TTenantSettingsIndexRoute: TTenantSettingsIndexRoute,
}

const TTenantSettingsRouteWithChildren = TTenantSettingsRoute._addFileChildren(
  TTenantSettingsRouteChildren,
)

interface TTenantRouteChildren {
  TTenantAiRoute: typeof TTenantAiRouteWithChildren
  TTenantApiExplorerRoute: typeof TTenantApiExplorerRoute
  TTenantClusterRoute: typeof TTenantClusterRoute
  TTenantDashboardRoute: typeof TTenantDashboardRoute
  TTenantDashboardsRoute: typeof TTenantDashboardsRouteWithChildren
  TTenantMiddlewaresRoute: typeof TTenantMiddlewaresRoute
  TTenantNotificationsRoute: typeof TTenantNotificationsRoute
  TTenantPluginsRoute: typeof TTenantPluginsRoute
  TTenantPoliciesRoute: typeof TTenantPoliciesRoute
  TTenantRoutesRoute: typeof TTenantRoutesRoute
  TTenantSecurityRoute: typeof TTenantSecurityRouteWithChildren
  TTenantServicesRoute: typeof TTenantServicesRoute
  TTenantSettingsRoute: typeof TTenantSettingsRouteWithChildren
  TTenantSitesRoute: typeof TTenantSitesRoute
  TTenantPluginsSignersRoute: typeof TTenantPluginsSignersRoute
  TTenantServicesServiceIdRoute: typeof TTenantServicesServiceIdRoute
  TTenantDetailKindIdRoute: typeof TTenantDetailKindIdRoute
  TTenantDashboardsDashboardIdEditRoute: typeof TTenantDashboardsDashboardIdEditRoute
}

const TTenantRouteChildren: TTenantRouteChildren = {
  TTenantAiRoute: TTenantAiRouteWithChildren,
  TTenantApiExplorerRoute: TTenantApiExplorerRoute,
  TTenantClusterRoute: TTenantClusterRoute,
  TTenantDashboardRoute: TTenantDashboardRoute,
  TTenantDashboardsRoute: TTenantDashboardsRouteWithChildren,
  TTenantMiddlewaresRoute: TTenantMiddlewaresRoute,
  TTenantNotificationsRoute: TTenantNotificationsRoute,
  TTenantPluginsRoute: TTenantPluginsRoute,
  TTenantPoliciesRoute: TTenantPoliciesRoute,
  TTenantRoutesRoute: TTenantRoutesRoute,
  TTenantSecurityRoute: TTenantSecurityRouteWithChildren,
  TTenantServicesRoute: TTenantServicesRoute,
  TTenantSettingsRoute: TTenantSettingsRouteWithChildren,
  TTenantSitesRoute: TTenantSitesRoute,
  TTenantPluginsSignersRoute: TTenantPluginsSignersRoute,
  TTenantServicesServiceIdRoute: TTenantServicesServiceIdRoute,
  TTenantDetailKindIdRoute: TTenantDetailKindIdRoute,
  TTenantDashboardsDashboardIdEditRoute: TTenantDashboardsDashboardIdEditRoute,
}

const TTenantRouteWithChildren =
  TTenantRoute._addFileChildren(TTenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UnauthRoute: UnauthRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  AdminRoute: AdminRouteWithChildren,
  TenantsRoute: TenantsRoute,
  PluginsSplatRoute: PluginsSplatRoute,
  TTenantRoute: TTenantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
