/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClusterRouteImport } from './routes/cluster'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrafficLiveRouteImport } from './routes/traffic/live'
import { Route as TrafficAnalyticsRouteImport } from './routes/traffic/analytics'
import { Route as TrafficAiRouteImport } from './routes/traffic/ai'
import { Route as SettingsUsersRouteImport } from './routes/settings/users'
import { Route as SettingsTlsRouteImport } from './routes/settings/tls'
import { Route as SettingsRolesRouteImport } from './routes/settings/roles'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPkiRouteImport } from './routes/settings/pki'
import { Route as SettingsObservabilityRouteImport } from './routes/settings/observability'
import { Route as SettingsNetworkRouteImport } from './routes/settings/network'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsDangerZoneRouteImport } from './routes/settings/danger-zone'
import { Route as SettingsConfigStoreRouteImport } from './routes/settings/config-store'
import { Route as SettingsAuthenticationRouteImport } from './routes/settings/authentication'
import { Route as PluginsPluginIdRouteImport } from './routes/plugins/$pluginId'
import { Route as ConfigPoliciesRouteImport } from './routes/config/policies'
import { Route as SecurityUsersIndexRouteImport } from './routes/security/users.index'
import { Route as SecurityRolesIndexRouteImport } from './routes/security/roles.index'
import { Route as SecurityApiKeysIndexRouteImport } from './routes/security/api-keys.index'
import { Route as SecurityAccessPoliciesIndexRouteImport } from './routes/security/access-policies.index'
import { Route as ConfigServicesIndexRouteImport } from './routes/config/services.index'
import { Route as ConfigRoutesIndexRouteImport } from './routes/config/routes.index'
import { Route as ConfigPoliciesIndexRouteImport } from './routes/config/policies.index'
import { Route as SecurityUsersUserIdRouteImport } from './routes/security/users.$userId'
import { Route as SecurityRolesRoleIdRouteImport } from './routes/security/roles.$roleId'
import { Route as SecurityApiKeysKeyIdRouteImport } from './routes/security/api-keys.$keyId'
import { Route as SecurityAccessPoliciesCreateRouteImport } from './routes/security/access-policies.create'
import { Route as ConfigServicesCreateRouteImport } from './routes/config/services.create'
import { Route as ConfigServicesServiceIdRouteImport } from './routes/config/services.$serviceId'
import { Route as ConfigRoutesCreateRouteImport } from './routes/config/routes.create'
import { Route as ConfigRoutesRouteIdRouteImport } from './routes/config/routes.$routeId'
import { Route as ConfigPoliciesCreateRouteImport } from './routes/config/policies.create'
import { Route as ConfigPoliciesPolicyIdRouteImport } from './routes/config/policies.$policyId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterRoute = ClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficLiveRoute = TrafficLiveRouteImport.update({
  id: '/traffic/live',
  path: '/traffic/live',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficAnalyticsRoute = TrafficAnalyticsRouteImport.update({
  id: '/traffic/analytics',
  path: '/traffic/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficAiRoute = TrafficAiRouteImport.update({
  id: '/traffic/ai',
  path: '/traffic/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTlsRoute = SettingsTlsRouteImport.update({
  id: '/tls',
  path: '/tls',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPkiRoute = SettingsPkiRouteImport.update({
  id: '/pki',
  path: '/pki',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsObservabilityRoute = SettingsObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNetworkRoute = SettingsNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDangerZoneRoute = SettingsDangerZoneRouteImport.update({
  id: '/danger-zone',
  path: '/danger-zone',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConfigStoreRoute = SettingsConfigStoreRouteImport.update({
  id: '/config-store',
  path: '/config-store',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAuthenticationRoute = SettingsAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => SettingsRoute,
} as any)
const PluginsPluginIdRoute = PluginsPluginIdRouteImport.update({
  id: '/$pluginId',
  path: '/$pluginId',
  getParentRoute: () => PluginsRoute,
} as any)
const ConfigPoliciesRoute = ConfigPoliciesRouteImport.update({
  id: '/config/policies',
  path: '/config/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityUsersIndexRoute = SecurityUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => SecurityRoute,
} as any)
const SecurityRolesIndexRoute = SecurityRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => SecurityRoute,
} as any)
const SecurityApiKeysIndexRoute = SecurityApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => SecurityRoute,
} as any)
const SecurityAccessPoliciesIndexRoute =
  SecurityAccessPoliciesIndexRouteImport.update({
    id: '/access-policies/',
    path: '/access-policies/',
    getParentRoute: () => SecurityRoute,
  } as any)
const ConfigServicesIndexRoute = ConfigServicesIndexRouteImport.update({
  id: '/config/services/',
  path: '/config/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoutesIndexRoute = ConfigRoutesIndexRouteImport.update({
  id: '/config/routes/',
  path: '/config/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigPoliciesIndexRoute = ConfigPoliciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfigPoliciesRoute,
} as any)
const SecurityUsersUserIdRoute = SecurityUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => SecurityRoute,
} as any)
const SecurityRolesRoleIdRoute = SecurityRolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => SecurityRoute,
} as any)
const SecurityApiKeysKeyIdRoute = SecurityApiKeysKeyIdRouteImport.update({
  id: '/api-keys/$keyId',
  path: '/api-keys/$keyId',
  getParentRoute: () => SecurityRoute,
} as any)
const SecurityAccessPoliciesCreateRoute =
  SecurityAccessPoliciesCreateRouteImport.update({
    id: '/access-policies/create',
    path: '/access-policies/create',
    getParentRoute: () => SecurityRoute,
  } as any)
const ConfigServicesCreateRoute = ConfigServicesCreateRouteImport.update({
  id: '/config/services/create',
  path: '/config/services/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigServicesServiceIdRoute = ConfigServicesServiceIdRouteImport.update({
  id: '/config/services/$serviceId',
  path: '/config/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoutesCreateRoute = ConfigRoutesCreateRouteImport.update({
  id: '/config/routes/create',
  path: '/config/routes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoutesRouteIdRoute = ConfigRoutesRouteIdRouteImport.update({
  id: '/config/routes/$routeId',
  path: '/config/routes/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigPoliciesCreateRoute = ConfigPoliciesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ConfigPoliciesRoute,
} as any)
const ConfigPoliciesPolicyIdRoute = ConfigPoliciesPolicyIdRouteImport.update({
  id: '/$policyId',
  path: '/$policyId',
  getParentRoute: () => ConfigPoliciesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/certificates': typeof CertificatesRoute
  '/change-password': typeof ChangePasswordRoute
  '/cluster': typeof ClusterRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/security': typeof SecurityRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/config/policies': typeof ConfigPoliciesRouteWithChildren
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/settings/authentication': typeof SettingsAuthenticationRoute
  '/settings/config-store': typeof SettingsConfigStoreRoute
  '/settings/danger-zone': typeof SettingsDangerZoneRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/observability': typeof SettingsObservabilityRoute
  '/settings/pki': typeof SettingsPkiRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/tls': typeof SettingsTlsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/traffic/ai': typeof TrafficAiRoute
  '/traffic/analytics': typeof TrafficAnalyticsRoute
  '/traffic/live': typeof TrafficLiveRoute
  '/config/policies/$policyId': typeof ConfigPoliciesPolicyIdRoute
  '/config/policies/create': typeof ConfigPoliciesCreateRoute
  '/config/routes/$routeId': typeof ConfigRoutesRouteIdRoute
  '/config/routes/create': typeof ConfigRoutesCreateRoute
  '/config/services/$serviceId': typeof ConfigServicesServiceIdRoute
  '/config/services/create': typeof ConfigServicesCreateRoute
  '/security/access-policies/create': typeof SecurityAccessPoliciesCreateRoute
  '/security/api-keys/$keyId': typeof SecurityApiKeysKeyIdRoute
  '/security/roles/$roleId': typeof SecurityRolesRoleIdRoute
  '/security/users/$userId': typeof SecurityUsersUserIdRoute
  '/config/policies/': typeof ConfigPoliciesIndexRoute
  '/config/routes/': typeof ConfigRoutesIndexRoute
  '/config/services/': typeof ConfigServicesIndexRoute
  '/security/access-policies/': typeof SecurityAccessPoliciesIndexRoute
  '/security/api-keys/': typeof SecurityApiKeysIndexRoute
  '/security/roles/': typeof SecurityRolesIndexRoute
  '/security/users/': typeof SecurityUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/certificates': typeof CertificatesRoute
  '/change-password': typeof ChangePasswordRoute
  '/cluster': typeof ClusterRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/security': typeof SecurityRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/settings/authentication': typeof SettingsAuthenticationRoute
  '/settings/config-store': typeof SettingsConfigStoreRoute
  '/settings/danger-zone': typeof SettingsDangerZoneRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/observability': typeof SettingsObservabilityRoute
  '/settings/pki': typeof SettingsPkiRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/tls': typeof SettingsTlsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/traffic/ai': typeof TrafficAiRoute
  '/traffic/analytics': typeof TrafficAnalyticsRoute
  '/traffic/live': typeof TrafficLiveRoute
  '/config/policies/$policyId': typeof ConfigPoliciesPolicyIdRoute
  '/config/policies/create': typeof ConfigPoliciesCreateRoute
  '/config/routes/$routeId': typeof ConfigRoutesRouteIdRoute
  '/config/routes/create': typeof ConfigRoutesCreateRoute
  '/config/services/$serviceId': typeof ConfigServicesServiceIdRoute
  '/config/services/create': typeof ConfigServicesCreateRoute
  '/security/access-policies/create': typeof SecurityAccessPoliciesCreateRoute
  '/security/api-keys/$keyId': typeof SecurityApiKeysKeyIdRoute
  '/security/roles/$roleId': typeof SecurityRolesRoleIdRoute
  '/security/users/$userId': typeof SecurityUsersUserIdRoute
  '/config/policies': typeof ConfigPoliciesIndexRoute
  '/config/routes': typeof ConfigRoutesIndexRoute
  '/config/services': typeof ConfigServicesIndexRoute
  '/security/access-policies': typeof SecurityAccessPoliciesIndexRoute
  '/security/api-keys': typeof SecurityApiKeysIndexRoute
  '/security/roles': typeof SecurityRolesIndexRoute
  '/security/users': typeof SecurityUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/certificates': typeof CertificatesRoute
  '/change-password': typeof ChangePasswordRoute
  '/cluster': typeof ClusterRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/security': typeof SecurityRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/config/policies': typeof ConfigPoliciesRouteWithChildren
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/settings/authentication': typeof SettingsAuthenticationRoute
  '/settings/config-store': typeof SettingsConfigStoreRoute
  '/settings/danger-zone': typeof SettingsDangerZoneRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/observability': typeof SettingsObservabilityRoute
  '/settings/pki': typeof SettingsPkiRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/tls': typeof SettingsTlsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/traffic/ai': typeof TrafficAiRoute
  '/traffic/analytics': typeof TrafficAnalyticsRoute
  '/traffic/live': typeof TrafficLiveRoute
  '/config/policies/$policyId': typeof ConfigPoliciesPolicyIdRoute
  '/config/policies/create': typeof ConfigPoliciesCreateRoute
  '/config/routes/$routeId': typeof ConfigRoutesRouteIdRoute
  '/config/routes/create': typeof ConfigRoutesCreateRoute
  '/config/services/$serviceId': typeof ConfigServicesServiceIdRoute
  '/config/services/create': typeof ConfigServicesCreateRoute
  '/security/access-policies/create': typeof SecurityAccessPoliciesCreateRoute
  '/security/api-keys/$keyId': typeof SecurityApiKeysKeyIdRoute
  '/security/roles/$roleId': typeof SecurityRolesRoleIdRoute
  '/security/users/$userId': typeof SecurityUsersUserIdRoute
  '/config/policies/': typeof ConfigPoliciesIndexRoute
  '/config/routes/': typeof ConfigRoutesIndexRoute
  '/config/services/': typeof ConfigServicesIndexRoute
  '/security/access-policies/': typeof SecurityAccessPoliciesIndexRoute
  '/security/api-keys/': typeof SecurityApiKeysIndexRoute
  '/security/roles/': typeof SecurityRolesIndexRoute
  '/security/users/': typeof SecurityUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/certificates'
    | '/change-password'
    | '/cluster'
    | '/login'
    | '/plugins'
    | '/security'
    | '/settings'
    | '/config/policies'
    | '/plugins/$pluginId'
    | '/settings/authentication'
    | '/settings/config-store'
    | '/settings/danger-zone'
    | '/settings/general'
    | '/settings/network'
    | '/settings/observability'
    | '/settings/pki'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/tls'
    | '/settings/users'
    | '/traffic/ai'
    | '/traffic/analytics'
    | '/traffic/live'
    | '/config/policies/$policyId'
    | '/config/policies/create'
    | '/config/routes/$routeId'
    | '/config/routes/create'
    | '/config/services/$serviceId'
    | '/config/services/create'
    | '/security/access-policies/create'
    | '/security/api-keys/$keyId'
    | '/security/roles/$roleId'
    | '/security/users/$userId'
    | '/config/policies/'
    | '/config/routes/'
    | '/config/services/'
    | '/security/access-policies/'
    | '/security/api-keys/'
    | '/security/roles/'
    | '/security/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/certificates'
    | '/change-password'
    | '/cluster'
    | '/login'
    | '/plugins'
    | '/security'
    | '/settings'
    | '/plugins/$pluginId'
    | '/settings/authentication'
    | '/settings/config-store'
    | '/settings/danger-zone'
    | '/settings/general'
    | '/settings/network'
    | '/settings/observability'
    | '/settings/pki'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/tls'
    | '/settings/users'
    | '/traffic/ai'
    | '/traffic/analytics'
    | '/traffic/live'
    | '/config/policies/$policyId'
    | '/config/policies/create'
    | '/config/routes/$routeId'
    | '/config/routes/create'
    | '/config/services/$serviceId'
    | '/config/services/create'
    | '/security/access-policies/create'
    | '/security/api-keys/$keyId'
    | '/security/roles/$roleId'
    | '/security/users/$userId'
    | '/config/policies'
    | '/config/routes'
    | '/config/services'
    | '/security/access-policies'
    | '/security/api-keys'
    | '/security/roles'
    | '/security/users'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/certificates'
    | '/change-password'
    | '/cluster'
    | '/login'
    | '/plugins'
    | '/security'
    | '/settings'
    | '/config/policies'
    | '/plugins/$pluginId'
    | '/settings/authentication'
    | '/settings/config-store'
    | '/settings/danger-zone'
    | '/settings/general'
    | '/settings/network'
    | '/settings/observability'
    | '/settings/pki'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/tls'
    | '/settings/users'
    | '/traffic/ai'
    | '/traffic/analytics'
    | '/traffic/live'
    | '/config/policies/$policyId'
    | '/config/policies/create'
    | '/config/routes/$routeId'
    | '/config/routes/create'
    | '/config/services/$serviceId'
    | '/config/services/create'
    | '/security/access-policies/create'
    | '/security/api-keys/$keyId'
    | '/security/roles/$roleId'
    | '/security/users/$userId'
    | '/config/policies/'
    | '/config/routes/'
    | '/config/services/'
    | '/security/access-policies/'
    | '/security/api-keys/'
    | '/security/roles/'
    | '/security/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CertificatesRoute: typeof CertificatesRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ClusterRoute: typeof ClusterRoute
  LoginRoute: typeof LoginRoute
  PluginsRoute: typeof PluginsRouteWithChildren
  SecurityRoute: typeof SecurityRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  ConfigPoliciesRoute: typeof ConfigPoliciesRouteWithChildren
  TrafficAiRoute: typeof TrafficAiRoute
  TrafficAnalyticsRoute: typeof TrafficAnalyticsRoute
  TrafficLiveRoute: typeof TrafficLiveRoute
  ConfigRoutesRouteIdRoute: typeof ConfigRoutesRouteIdRoute
  ConfigRoutesCreateRoute: typeof ConfigRoutesCreateRoute
  ConfigServicesServiceIdRoute: typeof ConfigServicesServiceIdRoute
  ConfigServicesCreateRoute: typeof ConfigServicesCreateRoute
  ConfigRoutesIndexRoute: typeof ConfigRoutesIndexRoute
  ConfigServicesIndexRoute: typeof ConfigServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster': {
      id: '/cluster'
      path: '/cluster'
      fullPath: '/cluster'
      preLoaderRoute: typeof ClusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic/live': {
      id: '/traffic/live'
      path: '/traffic/live'
      fullPath: '/traffic/live'
      preLoaderRoute: typeof TrafficLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic/analytics': {
      id: '/traffic/analytics'
      path: '/traffic/analytics'
      fullPath: '/traffic/analytics'
      preLoaderRoute: typeof TrafficAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic/ai': {
      id: '/traffic/ai'
      path: '/traffic/ai'
      fullPath: '/traffic/ai'
      preLoaderRoute: typeof TrafficAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tls': {
      id: '/settings/tls'
      path: '/tls'
      fullPath: '/settings/tls'
      preLoaderRoute: typeof SettingsTlsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/pki': {
      id: '/settings/pki'
      path: '/pki'
      fullPath: '/settings/pki'
      preLoaderRoute: typeof SettingsPkiRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/observability': {
      id: '/settings/observability'
      path: '/observability'
      fullPath: '/settings/observability'
      preLoaderRoute: typeof SettingsObservabilityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/network': {
      id: '/settings/network'
      path: '/network'
      fullPath: '/settings/network'
      preLoaderRoute: typeof SettingsNetworkRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/danger-zone': {
      id: '/settings/danger-zone'
      path: '/danger-zone'
      fullPath: '/settings/danger-zone'
      preLoaderRoute: typeof SettingsDangerZoneRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/config-store': {
      id: '/settings/config-store'
      path: '/config-store'
      fullPath: '/settings/config-store'
      preLoaderRoute: typeof SettingsConfigStoreRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/authentication': {
      id: '/settings/authentication'
      path: '/authentication'
      fullPath: '/settings/authentication'
      preLoaderRoute: typeof SettingsAuthenticationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/plugins/$pluginId': {
      id: '/plugins/$pluginId'
      path: '/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof PluginsPluginIdRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/config/policies': {
      id: '/config/policies'
      path: '/config/policies'
      fullPath: '/config/policies'
      preLoaderRoute: typeof ConfigPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/users/': {
      id: '/security/users/'
      path: '/users'
      fullPath: '/security/users/'
      preLoaderRoute: typeof SecurityUsersIndexRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/roles/': {
      id: '/security/roles/'
      path: '/roles'
      fullPath: '/security/roles/'
      preLoaderRoute: typeof SecurityRolesIndexRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/api-keys/': {
      id: '/security/api-keys/'
      path: '/api-keys'
      fullPath: '/security/api-keys/'
      preLoaderRoute: typeof SecurityApiKeysIndexRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/access-policies/': {
      id: '/security/access-policies/'
      path: '/access-policies'
      fullPath: '/security/access-policies/'
      preLoaderRoute: typeof SecurityAccessPoliciesIndexRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/config/services/': {
      id: '/config/services/'
      path: '/config/services'
      fullPath: '/config/services/'
      preLoaderRoute: typeof ConfigServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/routes/': {
      id: '/config/routes/'
      path: '/config/routes'
      fullPath: '/config/routes/'
      preLoaderRoute: typeof ConfigRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/policies/': {
      id: '/config/policies/'
      path: '/'
      fullPath: '/config/policies/'
      preLoaderRoute: typeof ConfigPoliciesIndexRouteImport
      parentRoute: typeof ConfigPoliciesRoute
    }
    '/security/users/$userId': {
      id: '/security/users/$userId'
      path: '/users/$userId'
      fullPath: '/security/users/$userId'
      preLoaderRoute: typeof SecurityUsersUserIdRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/roles/$roleId': {
      id: '/security/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/security/roles/$roleId'
      preLoaderRoute: typeof SecurityRolesRoleIdRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/api-keys/$keyId': {
      id: '/security/api-keys/$keyId'
      path: '/api-keys/$keyId'
      fullPath: '/security/api-keys/$keyId'
      preLoaderRoute: typeof SecurityApiKeysKeyIdRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/access-policies/create': {
      id: '/security/access-policies/create'
      path: '/access-policies/create'
      fullPath: '/security/access-policies/create'
      preLoaderRoute: typeof SecurityAccessPoliciesCreateRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/config/services/create': {
      id: '/config/services/create'
      path: '/config/services/create'
      fullPath: '/config/services/create'
      preLoaderRoute: typeof ConfigServicesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/services/$serviceId': {
      id: '/config/services/$serviceId'
      path: '/config/services/$serviceId'
      fullPath: '/config/services/$serviceId'
      preLoaderRoute: typeof ConfigServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/routes/create': {
      id: '/config/routes/create'
      path: '/config/routes/create'
      fullPath: '/config/routes/create'
      preLoaderRoute: typeof ConfigRoutesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/routes/$routeId': {
      id: '/config/routes/$routeId'
      path: '/config/routes/$routeId'
      fullPath: '/config/routes/$routeId'
      preLoaderRoute: typeof ConfigRoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/policies/create': {
      id: '/config/policies/create'
      path: '/create'
      fullPath: '/config/policies/create'
      preLoaderRoute: typeof ConfigPoliciesCreateRouteImport
      parentRoute: typeof ConfigPoliciesRoute
    }
    '/config/policies/$policyId': {
      id: '/config/policies/$policyId'
      path: '/$policyId'
      fullPath: '/config/policies/$policyId'
      preLoaderRoute: typeof ConfigPoliciesPolicyIdRouteImport
      parentRoute: typeof ConfigPoliciesRoute
    }
  }
}

interface PluginsRouteChildren {
  PluginsPluginIdRoute: typeof PluginsPluginIdRoute
}

const PluginsRouteChildren: PluginsRouteChildren = {
  PluginsPluginIdRoute: PluginsPluginIdRoute,
}

const PluginsRouteWithChildren =
  PluginsRoute._addFileChildren(PluginsRouteChildren)

interface SecurityRouteChildren {
  SecurityAccessPoliciesCreateRoute: typeof SecurityAccessPoliciesCreateRoute
  SecurityApiKeysKeyIdRoute: typeof SecurityApiKeysKeyIdRoute
  SecurityRolesRoleIdRoute: typeof SecurityRolesRoleIdRoute
  SecurityUsersUserIdRoute: typeof SecurityUsersUserIdRoute
  SecurityAccessPoliciesIndexRoute: typeof SecurityAccessPoliciesIndexRoute
  SecurityApiKeysIndexRoute: typeof SecurityApiKeysIndexRoute
  SecurityRolesIndexRoute: typeof SecurityRolesIndexRoute
  SecurityUsersIndexRoute: typeof SecurityUsersIndexRoute
}

const SecurityRouteChildren: SecurityRouteChildren = {
  SecurityAccessPoliciesCreateRoute: SecurityAccessPoliciesCreateRoute,
  SecurityApiKeysKeyIdRoute: SecurityApiKeysKeyIdRoute,
  SecurityRolesRoleIdRoute: SecurityRolesRoleIdRoute,
  SecurityUsersUserIdRoute: SecurityUsersUserIdRoute,
  SecurityAccessPoliciesIndexRoute: SecurityAccessPoliciesIndexRoute,
  SecurityApiKeysIndexRoute: SecurityApiKeysIndexRoute,
  SecurityRolesIndexRoute: SecurityRolesIndexRoute,
  SecurityUsersIndexRoute: SecurityUsersIndexRoute,
}

const SecurityRouteWithChildren = SecurityRoute._addFileChildren(
  SecurityRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAuthenticationRoute: typeof SettingsAuthenticationRoute
  SettingsConfigStoreRoute: typeof SettingsConfigStoreRoute
  SettingsDangerZoneRoute: typeof SettingsDangerZoneRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsNetworkRoute: typeof SettingsNetworkRoute
  SettingsObservabilityRoute: typeof SettingsObservabilityRoute
  SettingsPkiRoute: typeof SettingsPkiRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsTlsRoute: typeof SettingsTlsRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAuthenticationRoute: SettingsAuthenticationRoute,
  SettingsConfigStoreRoute: SettingsConfigStoreRoute,
  SettingsDangerZoneRoute: SettingsDangerZoneRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsNetworkRoute: SettingsNetworkRoute,
  SettingsObservabilityRoute: SettingsObservabilityRoute,
  SettingsPkiRoute: SettingsPkiRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsTlsRoute: SettingsTlsRoute,
  SettingsUsersRoute: SettingsUsersRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ConfigPoliciesRouteChildren {
  ConfigPoliciesPolicyIdRoute: typeof ConfigPoliciesPolicyIdRoute
  ConfigPoliciesCreateRoute: typeof ConfigPoliciesCreateRoute
  ConfigPoliciesIndexRoute: typeof ConfigPoliciesIndexRoute
}

const ConfigPoliciesRouteChildren: ConfigPoliciesRouteChildren = {
  ConfigPoliciesPolicyIdRoute: ConfigPoliciesPolicyIdRoute,
  ConfigPoliciesCreateRoute: ConfigPoliciesCreateRoute,
  ConfigPoliciesIndexRoute: ConfigPoliciesIndexRoute,
}

const ConfigPoliciesRouteWithChildren = ConfigPoliciesRoute._addFileChildren(
  ConfigPoliciesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CertificatesRoute: CertificatesRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ClusterRoute: ClusterRoute,
  LoginRoute: LoginRoute,
  PluginsRoute: PluginsRouteWithChildren,
  SecurityRoute: SecurityRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  ConfigPoliciesRoute: ConfigPoliciesRouteWithChildren,
  TrafficAiRoute: TrafficAiRoute,
  TrafficAnalyticsRoute: TrafficAnalyticsRoute,
  TrafficLiveRoute: TrafficLiveRoute,
  ConfigRoutesRouteIdRoute: ConfigRoutesRouteIdRoute,
  ConfigRoutesCreateRoute: ConfigRoutesCreateRoute,
  ConfigServicesServiceIdRoute: ConfigServicesServiceIdRoute,
  ConfigServicesCreateRoute: ConfigServicesCreateRoute,
  ConfigRoutesIndexRoute: ConfigRoutesIndexRoute,
  ConfigServicesIndexRoute: ConfigServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
