/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClusterRouteImport } from './routes/cluster'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrafficLiveRouteImport } from './routes/traffic/live'
import { Route as TrafficAnalyticsRouteImport } from './routes/traffic/analytics'
import { Route as TrafficAiRouteImport } from './routes/traffic/ai'
import { Route as SettingsUsersRouteImport } from './routes/settings/users'
import { Route as SettingsTlsRouteImport } from './routes/settings/tls'
import { Route as SettingsRolesRouteImport } from './routes/settings/roles'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPkiRouteImport } from './routes/settings/pki'
import { Route as SettingsObservabilityRouteImport } from './routes/settings/observability'
import { Route as SettingsNetworkRouteImport } from './routes/settings/network'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsDangerZoneRouteImport } from './routes/settings/danger-zone'
import { Route as SettingsConfigStoreRouteImport } from './routes/settings/config-store'
import { Route as SettingsAuthenticationRouteImport } from './routes/settings/authentication'
import { Route as PluginsPluginIdRouteImport } from './routes/plugins/$pluginId'
import { Route as ConfigServicesRouteImport } from './routes/config/services'
import { Route as ConfigRoutesRouteImport } from './routes/config/routes'
import { Route as ConfigPoliciesRouteImport } from './routes/config/policies'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterRoute = ClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficLiveRoute = TrafficLiveRouteImport.update({
  id: '/traffic/live',
  path: '/traffic/live',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficAnalyticsRoute = TrafficAnalyticsRouteImport.update({
  id: '/traffic/analytics',
  path: '/traffic/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficAiRoute = TrafficAiRouteImport.update({
  id: '/traffic/ai',
  path: '/traffic/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTlsRoute = SettingsTlsRouteImport.update({
  id: '/tls',
  path: '/tls',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPkiRoute = SettingsPkiRouteImport.update({
  id: '/pki',
  path: '/pki',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsObservabilityRoute = SettingsObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNetworkRoute = SettingsNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDangerZoneRoute = SettingsDangerZoneRouteImport.update({
  id: '/danger-zone',
  path: '/danger-zone',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConfigStoreRoute = SettingsConfigStoreRouteImport.update({
  id: '/config-store',
  path: '/config-store',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAuthenticationRoute = SettingsAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => SettingsRoute,
} as any)
const PluginsPluginIdRoute = PluginsPluginIdRouteImport.update({
  id: '/$pluginId',
  path: '/$pluginId',
  getParentRoute: () => PluginsRoute,
} as any)
const ConfigServicesRoute = ConfigServicesRouteImport.update({
  id: '/config/services',
  path: '/config/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoutesRoute = ConfigRoutesRouteImport.update({
  id: '/config/routes',
  path: '/config/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigPoliciesRoute = ConfigPoliciesRouteImport.update({
  id: '/config/policies',
  path: '/config/policies',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/certificates': typeof CertificatesRoute
  '/change-password': typeof ChangePasswordRoute
  '/cluster': typeof ClusterRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRouteWithChildren
  '/config/policies': typeof ConfigPoliciesRoute
  '/config/routes': typeof ConfigRoutesRoute
  '/config/services': typeof ConfigServicesRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/settings/authentication': typeof SettingsAuthenticationRoute
  '/settings/config-store': typeof SettingsConfigStoreRoute
  '/settings/danger-zone': typeof SettingsDangerZoneRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/observability': typeof SettingsObservabilityRoute
  '/settings/pki': typeof SettingsPkiRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/tls': typeof SettingsTlsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/traffic/ai': typeof TrafficAiRoute
  '/traffic/analytics': typeof TrafficAnalyticsRoute
  '/traffic/live': typeof TrafficLiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/certificates': typeof CertificatesRoute
  '/change-password': typeof ChangePasswordRoute
  '/cluster': typeof ClusterRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRouteWithChildren
  '/config/policies': typeof ConfigPoliciesRoute
  '/config/routes': typeof ConfigRoutesRoute
  '/config/services': typeof ConfigServicesRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/settings/authentication': typeof SettingsAuthenticationRoute
  '/settings/config-store': typeof SettingsConfigStoreRoute
  '/settings/danger-zone': typeof SettingsDangerZoneRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/observability': typeof SettingsObservabilityRoute
  '/settings/pki': typeof SettingsPkiRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/tls': typeof SettingsTlsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/traffic/ai': typeof TrafficAiRoute
  '/traffic/analytics': typeof TrafficAnalyticsRoute
  '/traffic/live': typeof TrafficLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/certificates': typeof CertificatesRoute
  '/change-password': typeof ChangePasswordRoute
  '/cluster': typeof ClusterRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRouteWithChildren
  '/config/policies': typeof ConfigPoliciesRoute
  '/config/routes': typeof ConfigRoutesRoute
  '/config/services': typeof ConfigServicesRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/settings/authentication': typeof SettingsAuthenticationRoute
  '/settings/config-store': typeof SettingsConfigStoreRoute
  '/settings/danger-zone': typeof SettingsDangerZoneRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/observability': typeof SettingsObservabilityRoute
  '/settings/pki': typeof SettingsPkiRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/tls': typeof SettingsTlsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/traffic/ai': typeof TrafficAiRoute
  '/traffic/analytics': typeof TrafficAnalyticsRoute
  '/traffic/live': typeof TrafficLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/certificates'
    | '/change-password'
    | '/cluster'
    | '/login'
    | '/plugins'
    | '/security'
    | '/settings'
    | '/config/policies'
    | '/config/routes'
    | '/config/services'
    | '/plugins/$pluginId'
    | '/settings/authentication'
    | '/settings/config-store'
    | '/settings/danger-zone'
    | '/settings/general'
    | '/settings/network'
    | '/settings/observability'
    | '/settings/pki'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/tls'
    | '/settings/users'
    | '/traffic/ai'
    | '/traffic/analytics'
    | '/traffic/live'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/certificates'
    | '/change-password'
    | '/cluster'
    | '/login'
    | '/plugins'
    | '/security'
    | '/settings'
    | '/config/policies'
    | '/config/routes'
    | '/config/services'
    | '/plugins/$pluginId'
    | '/settings/authentication'
    | '/settings/config-store'
    | '/settings/danger-zone'
    | '/settings/general'
    | '/settings/network'
    | '/settings/observability'
    | '/settings/pki'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/tls'
    | '/settings/users'
    | '/traffic/ai'
    | '/traffic/analytics'
    | '/traffic/live'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/certificates'
    | '/change-password'
    | '/cluster'
    | '/login'
    | '/plugins'
    | '/security'
    | '/settings'
    | '/config/policies'
    | '/config/routes'
    | '/config/services'
    | '/plugins/$pluginId'
    | '/settings/authentication'
    | '/settings/config-store'
    | '/settings/danger-zone'
    | '/settings/general'
    | '/settings/network'
    | '/settings/observability'
    | '/settings/pki'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/tls'
    | '/settings/users'
    | '/traffic/ai'
    | '/traffic/analytics'
    | '/traffic/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CertificatesRoute: typeof CertificatesRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ClusterRoute: typeof ClusterRoute
  LoginRoute: typeof LoginRoute
  PluginsRoute: typeof PluginsRouteWithChildren
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ConfigPoliciesRoute: typeof ConfigPoliciesRoute
  ConfigRoutesRoute: typeof ConfigRoutesRoute
  ConfigServicesRoute: typeof ConfigServicesRoute
  TrafficAiRoute: typeof TrafficAiRoute
  TrafficAnalyticsRoute: typeof TrafficAnalyticsRoute
  TrafficLiveRoute: typeof TrafficLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster': {
      id: '/cluster'
      path: '/cluster'
      fullPath: '/cluster'
      preLoaderRoute: typeof ClusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic/live': {
      id: '/traffic/live'
      path: '/traffic/live'
      fullPath: '/traffic/live'
      preLoaderRoute: typeof TrafficLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic/analytics': {
      id: '/traffic/analytics'
      path: '/traffic/analytics'
      fullPath: '/traffic/analytics'
      preLoaderRoute: typeof TrafficAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic/ai': {
      id: '/traffic/ai'
      path: '/traffic/ai'
      fullPath: '/traffic/ai'
      preLoaderRoute: typeof TrafficAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tls': {
      id: '/settings/tls'
      path: '/tls'
      fullPath: '/settings/tls'
      preLoaderRoute: typeof SettingsTlsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/pki': {
      id: '/settings/pki'
      path: '/pki'
      fullPath: '/settings/pki'
      preLoaderRoute: typeof SettingsPkiRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/observability': {
      id: '/settings/observability'
      path: '/observability'
      fullPath: '/settings/observability'
      preLoaderRoute: typeof SettingsObservabilityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/network': {
      id: '/settings/network'
      path: '/network'
      fullPath: '/settings/network'
      preLoaderRoute: typeof SettingsNetworkRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/danger-zone': {
      id: '/settings/danger-zone'
      path: '/danger-zone'
      fullPath: '/settings/danger-zone'
      preLoaderRoute: typeof SettingsDangerZoneRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/config-store': {
      id: '/settings/config-store'
      path: '/config-store'
      fullPath: '/settings/config-store'
      preLoaderRoute: typeof SettingsConfigStoreRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/authentication': {
      id: '/settings/authentication'
      path: '/authentication'
      fullPath: '/settings/authentication'
      preLoaderRoute: typeof SettingsAuthenticationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/plugins/$pluginId': {
      id: '/plugins/$pluginId'
      path: '/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof PluginsPluginIdRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/config/services': {
      id: '/config/services'
      path: '/config/services'
      fullPath: '/config/services'
      preLoaderRoute: typeof ConfigServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/routes': {
      id: '/config/routes'
      path: '/config/routes'
      fullPath: '/config/routes'
      preLoaderRoute: typeof ConfigRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/policies': {
      id: '/config/policies'
      path: '/config/policies'
      fullPath: '/config/policies'
      preLoaderRoute: typeof ConfigPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PluginsRouteChildren {
  PluginsPluginIdRoute: typeof PluginsPluginIdRoute
}

const PluginsRouteChildren: PluginsRouteChildren = {
  PluginsPluginIdRoute: PluginsPluginIdRoute,
}

const PluginsRouteWithChildren =
  PluginsRoute._addFileChildren(PluginsRouteChildren)

interface SettingsRouteChildren {
  SettingsAuthenticationRoute: typeof SettingsAuthenticationRoute
  SettingsConfigStoreRoute: typeof SettingsConfigStoreRoute
  SettingsDangerZoneRoute: typeof SettingsDangerZoneRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsNetworkRoute: typeof SettingsNetworkRoute
  SettingsObservabilityRoute: typeof SettingsObservabilityRoute
  SettingsPkiRoute: typeof SettingsPkiRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsTlsRoute: typeof SettingsTlsRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAuthenticationRoute: SettingsAuthenticationRoute,
  SettingsConfigStoreRoute: SettingsConfigStoreRoute,
  SettingsDangerZoneRoute: SettingsDangerZoneRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsNetworkRoute: SettingsNetworkRoute,
  SettingsObservabilityRoute: SettingsObservabilityRoute,
  SettingsPkiRoute: SettingsPkiRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsTlsRoute: SettingsTlsRoute,
  SettingsUsersRoute: SettingsUsersRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CertificatesRoute: CertificatesRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ClusterRoute: ClusterRoute,
  LoginRoute: LoginRoute,
  PluginsRoute: PluginsRouteWithChildren,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ConfigPoliciesRoute: ConfigPoliciesRoute,
  ConfigRoutesRoute: ConfigRoutesRoute,
  ConfigServicesRoute: ConfigServicesRoute,
  TrafficAiRoute: TrafficAiRoute,
  TrafficAnalyticsRoute: TrafficAnalyticsRoute,
  TrafficLiveRoute: TrafficLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
