import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  contribSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'generated-index', description: 'Start contributing to Rioku.'},
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Design',
      link: {type: 'generated-index', description: 'Architecture and design documents.'},
      items: [{type: 'autogenerated', dirName: 'design'}],
    },
    {
      type: 'category',
      label: 'Decisions',
      link: {type: 'generated-index', description: 'Architectural decisions and research spikes.'},
      items: [{type: 'autogenerated', dirName: 'decisions'}],
    },
    {
      type: 'category',
      label: 'Development',
      link: {type: 'generated-index', description: 'Coding guidelines and how-to guides.'},
      items: [{type: 'autogenerated', dirName: 'development'}],
    },
    {
      type: 'category',
      label: 'Operations',
      link: {type: 'generated-index', description: 'Operational guides and processes.'},
      items: [{type: 'autogenerated', dirName: 'operations'}],
    },
    {
      type: 'category',
      label: 'Roadmap',
      link: {type: 'generated-index', description: 'Project roadmap and open issues.'},
      items: [{type: 'autogenerated', dirName: 'roadmap'}],
    },
  ],
};

export default sidebars;
