import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  contribSidebar: [
    {
      type: 'category',
      label: 'Quick Start',
      link: {type: 'generated-index', description: 'Get started contributing to Rioku.'},
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {type: 'generated-index', description: 'Design documents and architectural overview.'},
      items: [
        {type: 'autogenerated', dirName: 'architecture'},
        {type: 'autogenerated', dirName: 'design'},
      ],
    },
    {
      type: 'category',
      label: 'APIs',
      link: {type: 'generated-index', description: 'API reference documentation.'},
      items: [],
    },
    {
      type: 'category',
      label: 'Operations',
      link: {type: 'generated-index', description: 'Operational guides and infrastructure.'},
      items: [{type: 'autogenerated', dirName: 'operations'}],
    },
    {
      type: 'category',
      label: 'Contributing',
      link: {type: 'generated-index', description: 'Coding guidelines and contribution process.'},
      items: [
        {type: 'autogenerated', dirName: 'contributing'},
        {type: 'autogenerated', dirName: 'development'},
      ],
    },
    {
      type: 'category',
      label: 'Decisions',
      link: {type: 'generated-index', description: 'Architectural decisions and research spikes.'},
      items: [{type: 'autogenerated', dirName: 'decisions'}],
    },
    {
      type: 'category',
      label: 'AI Development',
      link: {type: 'generated-index', description: 'AI-assisted development workflows and agent integration.'},
      items: [{type: 'autogenerated', dirName: 'ai-development'}],
    },
  ],
};

export default sidebars;
