import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'generated-index', description: 'Get up and running with Rioku.'},
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      link: {type: 'generated-index', description: 'Understand the building blocks of Rioku.'},
      items: [{type: 'autogenerated', dirName: 'core-concepts'}],
    },
    {
      type: 'category',
      label: 'Configuration',
      link: {type: 'generated-index', description: 'Configure Rioku for your environment.'},
      items: [{type: 'autogenerated', dirName: 'configuration'}],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'generated-index', description: 'Step-by-step guides for common tasks.'},
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: 'Security',
      link: {type: 'generated-index', description: 'Authentication, authorization, and access control.'},
      items: [{type: 'autogenerated', dirName: 'security'}],
    },
    {
      type: 'category',
      label: 'PKI & TLS',
      link: {type: 'generated-index', description: 'Certificate management and TLS configuration.'},
      items: [{type: 'autogenerated', dirName: 'pki-and-tls'}],
    },
    {
      type: 'category',
      label: 'Traffic & Observability',
      link: {type: 'generated-index', description: 'Monitor traffic, traces, and system health.'},
      items: [{type: 'autogenerated', dirName: 'traffic-and-observability'}],
    },
    {
      type: 'category',
      label: 'AI & Agentic',
      link: {type: 'generated-index', description: 'AI-native gateway features for LLM workloads.'},
      items: [{type: 'autogenerated', dirName: 'ai-and-agentic'}],
    },
    {
      type: 'category',
      label: 'Plugins',
      link: {type: 'generated-index', description: 'Extend Rioku with plugins.'},
      items: [{type: 'autogenerated', dirName: 'plugins'}],
    },
    {
      type: 'category',
      label: 'Clustering',
      link: {type: 'generated-index', description: 'Run Rioku in high-availability mode.'},
      items: [{type: 'autogenerated', dirName: 'clustering'}],
    },
    {
      type: 'category',
      label: 'Admin Panel',
      link: {type: 'generated-index', description: 'Web-based management interface.'},
      items: [{type: 'autogenerated', dirName: 'admin-panel'}],
    },
    {
      type: 'category',
      label: 'CLI Reference',
      link: {type: 'generated-index', description: 'Complete CLI command reference.'},
      items: [{type: 'autogenerated', dirName: 'cli-reference'}],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'generated-index', description: 'REST API endpoint reference.'},
      items: [{type: 'autogenerated', dirName: 'api-reference'}],
    },
    {
      type: 'category',
      label: 'Deployment',
      link: {type: 'generated-index', description: 'Deploy Rioku to production.'},
      items: [{type: 'autogenerated', dirName: 'deployment'}],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      link: {type: 'generated-index', description: 'Diagnose and fix common issues.'},
      items: [{type: 'autogenerated', dirName: 'troubleshooting'}],
    },
  ],
};

export default sidebars;
